### ISSUE TITLE
New Rule named-snapshot

### ISSUE THREAD

**Issue by dmiller9911** [jest-community/eslint-plugin-jest#103]
I was wondering if this repo would be open to a rule to enforce naming of snapshots.  Options would be `always | mutli | never`
* **always** - Enforce naming of snapshots even if there is only a singular snapshot.
* **multi** - Enforce naming only if there are multiple snapshots in a test. naming from [curly rule](eslint-plugin-jest)
* **never** - Disallow naming of snapshots

I would be more than happy to contribute this rule.  I plan to write it for one of my projects, and I wanted to check to make sure that this repo would be open to adding it before I open a PR.

**Comment by SimenB** [comment]
Yeah, I don't mind a rule for this.

Keep https://github.com/facebook/jest/issues/5847 in mind when implementing

**Comment by G-Rath** [comment]
I've created a PR for this which supports `always` and `multi`, with `multi` being the default.
