### ISSUE TITLE
[new-rule] prefer `.each`

### ISSUE THREAD

**Issue by G-Rath** [jest-community/eslint-plugin-jest#1048]
Raised [in this comment](https://github.com/jest-community/eslint-plugin-jest/issues/1047#issuecomment-1030456417).

I think we could get away with a basic check where we look for a loop (or `forEach`) either at the top level of a file or within a `describe` (to ensure that we still "allow" loops to be used e.g. within `it`s themselves).

This rule would only really be of benefit if it was included as a recommended rule.

**Comment by Ariane-B** [comment]
You'd probably have to make sure that forEach is excluded from require-hook warnings to avoid having them be flagged for two errors at once.

Anyway, since `for` loops are not flagged by it currently, it would just be consistent, I think.

**Comment by G-Rath** [comment]
Generally, rules shouldn't have special cases based on expecting them to be reported by other rules as there's no guarantee that the other rules are enabled so it's fine to have two rules reporting on the same bit of code.

The fact that the contents of `for` loops are not flagged is a bug - thinking about it, maybe instead of a new rule we should have `require-hook` mention using `.each` in it's message when reporting on loops 🤔
