### ISSUE TITLE
expectObservable from testScheduler throws jest/expect-expect error and jasmine marbles

### ISSUE THREAD

**Issue by Yohandah** [jest-community/eslint-plugin-jest#1055]
```
testScheduler.run((helpers) => {
      const { hot, cold, expectObservable } = helpers;
      expectObservable(effects.login$).toBe('--(b)', { b: completion });
    });
```

This test returns Test has no assertions(jest/expect-expect) while there is an assertion. Same when you use toBeObservable from jasmine-marbles

**Comment by G-Rath** [comment]
`expect-expect` expects you to be using `expect` since that's the Jest method for doing assertions - you can use [`assertFunctionNames`](https://github.com/jest-community/eslint-plugin-jest/blob/main/docs/rules/expect-expect.md#assertfunctionnames) to specify custom assertion methods.
