### ISSUE TITLE
Fix toBe(true|false) -> toBeTrue|toBeFalse

### ISSUE THREAD

**Issue by ilyub** [jest-community/eslint-plugin-jest#1102]
Described in the subject

**Comment by G-Rath** [comment]
In future could you please properly describe what you're actually wanting, ideally with an example or two?

I'm assuming you're wanting us to support transforming uses of the `toBe` matcher with boolean values to the matchers provides by `jest-extended`.

We don't support `jest-extended` matchers - instead you want `eslint-plugin-jest-extended`, where I've actually already implemented this rule.

Unfortunately @mattphillips is the only one that has publishing permissions for that package on npm and I've not been able to get a publishing token or ci setup with him.
