### ISSUE TITLE
[expect-expect] assertFunctionNames - RegEx does not handle functions with numbers in the signature

### ISSUE THREAD

**Issue by EthanPrentice** [jest-community/eslint-plugin-jest#1103]
I have a function with the signature `expect404ToBeLoaded()` which wasn't matching the wildcard `expect*` in `assertFunctionNames` like I thought it should.  Looking at the source code it looks like the matching is only done on `[a-Z]`.  Is there a reason for this, or would it make sense to update this to include `[0-9]`?

https://github.com/jest-community/eslint-plugin-jest/blob/f328c47972ffa0edfcd66597c226ba1ecef68932/src/rules/expect-expect.ts#L22-L39

**Comment by G-Rath** [comment]
yup that's a bug
