### ISSUE TITLE
`@typescript-eslint/utils` causes missing peer dependencies warning

### ISSUE THREAD

**Issue by nilzona** [jest-community/eslint-plugin-jest#1117]
if `eslint-plugin-jest` is used in a non-typescript project you will get "Unmet peer dependencies" warnings because of `@typescript-eslint/utils` being specified in the dependencies and that one has a peerDependency to `typescript`.

From what I can see it's being used to import types and enums which is handy in typescript source code, but doesn't it make more sense to have it as a dev dependency?

**Comment by SimenB** [comment]
This is https://github.com/typescript-eslint/typescript-eslint/issues/3309 - feel free to open a new issue over there (or maybe https://github.com/typescript-eslint/typescript-eslint/issues/3622 is applicable). Regardless, it's an issue in that repo
