### ISSUE TITLE
[new rule] strict formatting for describe and test blocks

### ISSUE THREAD

**Issue by eddiesholl** [jest-community/eslint-plugin-jest#113]
We would really like to enforce some strict formatting for the various parts of jest test syntax. I'm not sure if these would be general enough to be considered useful, but they seem like a nice way to help ensure test code is nicely structured. An example of my teams desired syntax is:
```
describe('some tests', () => {
  let varName

  beforeEach(() => {
    let varName = 'foo'
  })

  it('does something cool', () => {
    const result = callAFuncWith(varName)
    result.wow()

    expect(result).toBeAwesome()
  })
})
```
Seperate rules could enforce:
- a blank line after describe level lets
- a blank line after a beforeEach
- a blank line between an expect and test setup statements

Another option would be a new 'eslint-jest-formatting' package.

**Comment by SimenB** [comment]
We landed on not including any formatting rules in #17. Then again, I don't really _mind_ them - they don't really hurt. And personally I really like organising tests into a when-given-then format, so I'd like rules like that.

Soooooo, PR welcome? :D

@thymikee holler if you disagree

**Comment by thymikee** [comment]
As long as it's not a default, I'm on board ;)

**Comment by SimenB** [comment]
Yeah, agreed. Should not be part of `recommended`

**Comment by SimenB** [comment]
See https://github.com/dangreenisrael/eslint-plugin-jest-formatting
