### ISSUE TITLE
false positive lint error introduced between 26.1.5 and 26.4.2

### ISSUE THREAD

**Issue by mo** [jest-community/eslint-plugin-jest#1130]
When I upgraded from 26.1.5 to 26.4.2 I started to get this false positive:
![image](https://user-images.githubusercontent.com/7117/170880156-909f89fd-2e6b-4acd-a32d-9b2f6cb80e65.png)

**Comment by G-Rath** [comment]
Thanks, this is the bug we suspected was in #1128.

In future, could you please include a text copy of your code rather than just a screenshot? Otherwise we have to retype it all out when trying to reproduce and build tests cases.
