### ISSUE TITLE
[no-disabled-tests] false positive on todo tests

### ISSUE THREAD

**Issue by waltherjj** [jest-community/eslint-plugin-jest#1136]
**What happens**

We upgraded from 26.2.1 to 26.4.5 and are now seeing `error  Test is missing function argument  jest/no-disabled-tests` for tests marked as todos: `it.todo('does something')`. I guess this could have been introduced in 26.4.1 or 26.4.2 by switching to jest function call parser? 

**What is expected**

`no-disabled-tests` should not report tests marked as todos.

Thanks for your time!

**Comment by G-Rath** [comment]
Ah yup thanks, I forgot to account for that when doing #1115
