### ISSUE TITLE
[valid-expect] include fixer for adding missing await

### ISSUE THREAD

**Issue by jayu** [jest-community/eslint-plugin-jest#1140]
How do you feel about making `jest/valid-expect` rule fixable for cases where `await` is missing ?

So adding `await` in front of `expect` in such cases:
```ts
it('should', async () => {
   expect(someAsyncThing).rejects.toBe(whatever)
})

//or 

it('should', async () => {
   expect(someAsyncThing).resolves.toBe(whatever)
})
```

Fixed code then would look like

```ts
it('should', async () => {
   await expect(someAsyncThing).rejects.toBe(whatever)
})

//or 

it('should', async () => {
   await expect(someAsyncThing).resolves.toBe(whatever)
})
```

I'm happy to give it a try if there is a chance it will be merged :)

**Comment by G-Rath** [comment]
Yup sounds good - we probably should have it as a suggestion if the function isn't already `async`.

**Comment by y-hsgw** [comment]
@G-Rath As for the remaining tasks for this issue, would it be appropriate to [suggest](https://eslint.org/docs/latest/extend/custom-rules#providing-suggestions) that if the target for validation is not async?


```ts
it('should', async () => {
  const someAsyncThing = () => { ... }
  expect(someAsyncThing).rejects.toBe(whatever)
})
```

**Comment by G-Rath** [comment]
@y-hsgw if you mean suggesting adding `await` regardless of if `async` is present, then yeah that's probably fine; though I think we should be able to successfully add `async` to at least some patterns.

Broadly speaking the logic should be something like:
1. find the closest function expression upwards in the tree (I'm pretty sure that's what `findFirstAsyncFunction` does exactly except it also checks if its `async`; but worth double checking)
2. if it is not `async`, include making a fixer for making it `async`
3. if the line has a `return` and ... etc (all the current fixer behaviour)
4. include a fixer for adding `await`

While it might seem complicated on the face, I'm actually pretty sure we should be able to always accurately know and fix `async/await`.

I'm happy to do incremental improvement PRs too, so we can aim for addressing the simple cases and then a followup PR for handling more complex ones
