### ISSUE TITLE
[no-standalone-expect]: false positive on `expect.<method>()`

### ISSUE THREAD

**Issue by mrtnzlml** [jest-community/eslint-plugin-jest#1186]
Hey, I received an update with the latest version 26.8.0 (https://github.com/adeira/universe/pull/4859); however, it seems to be throwing false errors:

<img width="534" alt="Screen Shot 2022-08-07 at 15 07 21" src="https://user-images.githubusercontent.com/978368/183309265-597feb74-6721-4caa-87ab-aafb00112bcd.png">

To my knowledge, `addSnapshotSerializer` should be outside of the test block (see: https://jestjs.io/docs/expect#expectaddsnapshotserializerserializer). Is my code wrong? Is this a bug in the latest release? 🤔 

Thanks for having a look! 😎

**Comment by G-Rath** [comment]
Per my comment [here], I think we should probably change `no-standalone-expect` to only care about `expect.hasAssertions` & `expect.assertions`

**Comment by G-Rath** [comment]
I'm going to change the logic tomorrow to what I said in my last comment - I should be able to get this landed tomorrow morning (NZST)

**Comment by alopix** [comment]
Saw the same behaviour for `expect.extend()` which you would definitely expect to call outside of a test block—specifically in the global jest setup.
