### ISSUE TITLE
[max-expects] now considers expect.assertions(n) an expect call

### ISSUE THREAD

**Issue by short-dsb** [jest-community/eslint-plugin-jest#1193]
The behavior in 26.8.1 changed from 26.7.0 to include `expect.assertions` when counting `expect` calls. This seems at odds with the purpose of `expect.assertions` to verify the number of intended `expect` calls. In 26.8.1, this means either dropping the verification or dropping a different `expect`, neither of which seem ideal.

My suggestions (in order of personal preference):
* Restore the behavior present in 26.7.0 and ignore `expect.assertions` calls when counting `max-expects`.
* Provide an option to restore the previous behavior, e.g., `ignoreExpectAssertions: boolean`.
* Update the [documentation](https://github.com/jest-community/eslint-plugin-jest/blob/v26.8.1/docs/rules/max-expects.md) and [tests](https://github.com/jest-community/eslint-plugin-jest/blob/main/src/rules/__tests__/max-expects.test.ts) to demonstrate the new behavior.

Thanks for your time and consideration. 🙂

**Comment by G-Rath** [comment]
Yup that's the same sort of thing as #1186 - we shouldn't count `expect.<member>()` as assertion calls.

**Comment by sir-gon** [comment]
This is a bit annoying...

All my 5-assertion tests are broken now, because is counting 6 (???).

This is my example explicitly says 5 assertions:

https://github.com/sir-gon/projecteuler-js/blob/main/src/helpers/bigNumbers.test.js#L44-L62

```

  it('bigSumMany examples', () => {
    expect.assertions(5);

    expect(bigSumMany(['2', '2'])).toBe('4');
    expect(bigSumMany(['123', '321'])).toBe('444');

    expect(bigSumMany(['2', '2', '2'])).toBe('6');

    expect(bigSumMany(['349', '854', '213', '543'])).toBe('1959');

    expect(
      bigSumMany([
        '12345678901234567890',
        '12345678901234567890',
        '12345678901234567890',
        '12345678901234567890'
      ])
    ).toBe('49382715604938271560');
  });
```

**Comment by G-Rath** [comment]
@sir-gon PRs are always welcome; otherwise I'll try and get this resolved myself tonight once I'm off work 🙂

**Comment by short-dsb** [comment]
Thanks for the quick fix, @G-Rath! Your work is appreciated. 🙂
