### ISSUE TITLE
[new rule] prefer toBe(false) and toBe(true) over toBeFalsy() and toBeTruthy() for primitive booleans

### ISSUE THREAD

**Issue by rubiesonthesky** [jest-community/eslint-plugin-jest#1228]
I thought I have seen this kind of rule somewhere, but it may be that I'm confusing it with jest extended rules `toBeTrue()` and `toBeFalse()`.

I think it would be helpful if there was rule that would suggest using `toBe(true | false)` instead of `toBeTruthy()` / `toBeFalsy()` when checking boolean values.

This kind of rule would help to catch some cases, where actual need is to check if the value is true / false, and not just truthy / falsy. 

I'm not sure would this rule need typescript support or not. Prefer-to-be rule does not need typescript support, so maybe this would also not need it?

I think in some cases, `toBeFalsy()` actually should be `toBeUndefined() / toBeNull()` but that should probably need to be another rule and is probably something that can be easily checked with linter.

**Comment by G-Rath** [comment]
We use to have this as a rule but it was replaced with the more flexible  https://github.com/jest-community/eslint-plugin-jest/blob/main/docs/rules/no-restricted-matchers.md
