### ISSUE TITLE
New rule to disallow using mock API in end-to-end test files

### ISSUE THREAD

**Issue by mrazauskas** [jest-community/eslint-plugin-jest#1256]
What about adding a rule which would disallows using mock APIs? I though it could be activated for a directory where end-to-end tests live and could ensure that test fixtures are used instead of mocks.

Usually I prefer to leave mocks and spies for unit tests and to avoid them in end-to-end tests. Just wanted to check what people smarter than me think? (;

**Comment by SimenB** [comment]
I think a rule disallowing using module mocking makes sense. Would you also want fake time, `jest.fn` etc to be disallowed, or only `jest.mock`, `jest.doMock` etc.?

**Comment by mrazauskas** [comment]
Let’s think.

`jest.fn`, `jest.mock`, `jest.spyOn`, `jest.doMock`, `jest.setMock` – are good candidates be banned.

Disallowing fake time sounds tricky. I think there should be an option allowing to ban everything except faking time. Testing server side APIs or web apps might depend on fake time in the end-to-end tests. In general it sounds good to have this configuration option.

**Comment by SimenB** [comment]
Sounds like you want to ban usage of `jest.*` in general. What APIs would you want? Only thing I can think of that's not mocking modules or mocking time is `jest.retryTimes` - at which point that one usage can probably be enabled via an eslint comment

**Comment by G-Rath** [comment]
It sounds like we should do a `no-restricted-jest-methods` to complement `no-restricted-matchers`, and then you'd want to use both together for your specific use-case (as you'd want to disable use of matchers like `toHaveBeenCalled`)

**Comment by mrazauskas** [comment]
Yep. That sounds right.

Actually my first idea was to suggest adding `no-restricted-jest-methods`, but it felt too abstract. The purpose did not look clear. Now after comments from Simen and you, I see that the first idea was right. The rest was pure overthinking ;D
