### ISSUE TITLE
Update eslint dependency to version 5.x

### ISSUE THREAD

**Issue by cwillwer** [jest-community/eslint-plugin-jest#127]
The version of eslint that this package uses is 4.10.0, which was released in October, 2017. The latest version as of filing this issue is 5.1.0. There have been at least 9 updates to the 4.x version, so at a minimum it should be updated to the lastest 4.x release, though moving to the 5.x version would be preferred.

**Comment by SimenB** [comment]
We only have a peer dependency, the 4.10 one is our own dev dependency. And the range of the peer dep should allow you to use whatever version you want 🙂 

https://github.com/jest-community/eslint-plugin-jest/blob/2b55a863cd092537abc9c89992ccf379671a4322/package.json#L26-L28

Happy to reopen if I misunderstood!
