### ISSUE TITLE
Manual extend without using "extends"

### ISSUE THREAD

**Issue by yvele** [jest-community/eslint-plugin-jest#128]
Unfortunately I cannot use the recommended `"extends": ["plugin:jest/recommended"]` method because I'm using glob override config and `extends` is not supported, see https://github.com/eslint/eslint/issues/8813

With **ESLint v4** that wasn't a problem I just did some "manual" extend like that:

```js
import { configs } from "eslint-plugin-jest";

export default {
  plugins : configs.recommended.plugins,
  env     : configs.recommended.env,
  "extends": [
    "plugin:jest/recommended"
  ]
  rules   : {
    ...configs.recommended.rules,
    ...OVERRIDES
  }
};
```

The problem came with **ESLint v5** where I get the same error as https://github.com/jest-community/eslint-plugin-jest/issues/44

```
Environment key "jest/globals" is unknown
```

And I cannot @pauloborges use [answer](https://github.com/jest-community/eslint-plugin-jest/issues/44#issuecomment-355504700) because of the [glob override config and `extends` issue](https://github.com/eslint/eslint/issues/8813).

Is there a workaround? Why is this `Environment key "jest/globals" is unknown` appearing with ESLint v5? Is there a way to manually register `jest/globals`?

I'm a bit stuck 🤔

**Comment by yvele** [comment]
Ok I found a workaround, instead of using

```js
      env: configs.recommended.env
```

Which is the exact same as

```js
      env: {
        'jest/globals': true
      }
```

I'm actually using 

```js
      env: {
        'jest': true
      }
```

As described in https://eslint.org/docs/user-guide/configuring#specifying-environments

I let this issue open to make sure someone see it.. There maybe is a real problem.

Feel free to close

**Comment by SimenB** [comment]
Note that the `jest` globals from eslint are not matching the ones we have in our own list.

Not sure why it doesn't work normally, though

**Comment by Graham42** [comment]
I'm also seeing 
>Environment key "jest/globals" is unknown
with config
```js
module.exports = {
  //...
  overrides: [
    {
      files: ["**/__tests__/**/*"],
      plugins: ["jest"],
      env: {
        "jest/globals": true,
      },
    },
  ]
}
```

versions:
eslint@5.15.1
eslint-plugin-jest@22.3.2

**Comment by alias-mac** [comment]
Just for the record (in case someone has the same problem that I have) I was able to make this work by doing:
```js
Object.assign({}, require('eslint-plugin-jest').configs.recommended, {
  files: ['node-tests/**/*.js'],
  plugins: ['jest'],
  env: {
    browser: false,
    node: true,
    jest: true,
  },
})
```

if I remove the `env` override, then it breaks like it is explained in comments above:
```js
Object.assign({}, require('eslint-plugin-jest').configs.recommended, {
  files: ['node-tests/**/*.js'],
  plugins: ['jest'],
})
```

**Comment by hon2a** [comment]
Please note that support for `extends` in `overrides` has been added in ESLint 6. (So this may likely be closed.)

**Comment by G-Rath** [comment]
Closing, since we're on ESLint 7 now.
