### ISSUE TITLE
[new rule] Rule to enforce return after expect (code written)

### ISSUE THREAD

**Issue by TheJaredWilcurt** [jest-community/eslint-plugin-jest#1301]
```js
// BAD
expect(x).toEqual(y);

// GOOD
expect(x)
  .toEqual(y);
```

**Auto-fixable:** yes

**Code:**

https://github.com/tjw-lint/eslint-config-tjw-jest/blob/main/custom-eslint-rules/newline-before-expect-assertion.js

**Comment by G-Rath** [comment]
This is more suitable for [`eslint-plugin-jest-formatting`](https://github.com/dangreenisrael/eslint-plugin-jest-formatting).

**Comment by G-Rath** [comment]
Closing per the above
