### ISSUE TITLE
[new rule] Capitalize test name (code written)

### ISSUE THREAD

**Issue by TheJaredWilcurt** [jest-community/eslint-plugin-jest#1302]
```js
// BAD
test('renders correctly', () => {
  expect(wrapper)
    .toMatchSnapshot();
});

// GOOD
test('Renders correctly', () => {
  expect(wrapper)
    .toMatchSnapshot();
});
```

**Auto-fixable:** yes

**Code:**

* https://github.com/tjw-lint/eslint-config-tjw-jest/blob/main/custom-eslint-rules/capitalize-test-names.js

**Comment by G-Rath** [comment]
This can be enforced with the [`mustMatch` and `mustNotMatch` options in `valid-title`](https://github.com/jest-community/eslint-plugin-jest/blob/main/docs/rules/valid-title.md#mustmatch--mustnotmatch) - I don't think there's a lot of value in supporting an autofix for this one case to justify the extra complexity.

**Comment by G-Rath** [comment]
Closing per the above
