### ISSUE TITLE
[new rule] Test names avoid "should" (code written)

### ISSUE THREAD

**Issue by TheJaredWilcurt** [jest-community/eslint-plugin-jest#1303]
Rule to enforce writing tests names in the style of [classic prose](https://www.youtube.com/watch?v=OV5J6BfToSw&t=22m11s) using the "active voice".

Most instances of the Passive Voice used in tests starting with "Should" can be automatically fixed. For example, all the following passive voices would become the displayed active voice alternative.

Passive voice                | Active voice
:--                          | :--
Should not have been called  | Was not called
Should not have errored      | Does not error
Should not error             | Does not error
Should be true if clicked    | Is true if clicked
Should have been called once | Called once
Should have exploded         | Explodes
Should correctly render      | Correctly renders
Should say x                 | Displays x
Should render correctly      | Renders correctly

**Auto-fixable:** Partially (the examples above)

**Code:**

* https://github.com/tjw-lint/eslint-config-tjw-jest/blob/main/custom-eslint-rules/test-names-avoid-should.js

**Comment by G-Rath** [comment]
This can be enforced with the [`mustMatch` and `mustNotMatch` options in `valid-title`](https://github.com/jest-community/eslint-plugin-jest/blob/main/docs/rules/valid-title.md#mustmatch--mustnotmatch) - I don't think there's a lot of value in supporting an autofix for this one case to justify the extra complexity.

**Comment by G-Rath** [comment]
Closing per the above
