### ISSUE TITLE
Add a rules to help with the `.toMatchNamedSnapshot()` matcher usage

### ISSUE THREAD

**Issue by mrazauskas** [jest-community/eslint-plugin-jest#1367]
From https://github.com/facebook/jest/pull/14045#issuecomment-1515923712

The linked PR is about to add `.toMatchNamedSnapshot()` matcher to Jest. The matcher works similar to `.toMatchSnapshot()`, but requires setting snapshot name explicitly that allows snapshot testing in `concurrent` mode (details of the problem https://github.com/facebook/jest/issues/2180).

After the PR lands, `eslint-plugin-jest` could be helpful by adding these rules:

- `no-duplicate-snapshot-names`: show error if the same snapshot name was used twice in a test file
- `prefer-named-snapshots`: require to use `.toMatchNamedSnapshot()` matcher with `test.concurrent` (or always)

---

This is just a note for discussion. No action required at the moment (;

**Comment by SimenB** [comment]
I think both of these rules sounds good. @G-Rath thoughts?

**Comment by G-Rath** [comment]
Yeah they sound reasonable (though I'd probably say go with `prefer-snapshot-name` to match nicely with `prefer-snapshot-hint`) - you could do `prefer-snapshot-name` with [`no-restricted-matchers`](https://github.com/jest-community/eslint-plugin-jest/blob/main/docs/rules/no-restricted-matchers.md), though that would be all or nothing and I guess it makes sense for us to tell people by default what to do when using `concurrent`

**Comment by mrazauskas** [comment]
The concurrent snapshots are now supported without adding new matcher (see https://github.com/jestjs/jest/pull/14139). So the rules will not be needed.

**Comment by muratkorkmaz106** [comment]
- [ ] ![image](https://github.com/jest-community/eslint-plugin-jest/assets/101784453/c799e883-3521-41e3-91c2-5e10a8778c55)
