### ISSUE TITLE
Unknown package installing eslint-plugin-jest

### ISSUE THREAD

**Issue by thechosenginger** [jest-community/eslint-plugin-jest#1378]
While downgrading a project from node v20 to 17.6.0 and npm to 8.5.1, came across an unsupported engine error with `eslint-plugin-jest@27.2.1`. I am not directly installing this package and have not been able to figure out where it is coming from. I have tried to remove both my package-lock and node_modules files and have also tried to add a downgraded version of the plugin to the package lock, but cannot get it to progress past an `npm install`. 

I am not looking to downgrade node any further as I would have to deal with issues in other packages, but i feel that is my only choice to move forward. 

npm ERR! code EBADENGINE
npm ERR! engine Unsupported engine
npm ERR! engine Not compatible with your version of node/npm: eslint-plugin-jest@27.2.1
npm ERR! notsup Not compatible with your version of node/npm: eslint-plugin-jest@27.2.1
npm ERR! notsup Required: {"node":"^14.15.0 || ^16.10.0 || >=18.0.0"}
npm ERR! notsup Actual:   {"npm":"8.5.1","node":"v17.6.0"}

**Comment by SimenB** [comment]
Not an issue with this plugin
