### ISSUE TITLE
Feature Request: Extend ESLint Plugin Jest for Custom Test and Describe Function Recognition

### ISSUE THREAD

**Issue by g-tiwari** [jest-community/eslint-plugin-jest#1417]
**Overview:**
I would like to propose a feature enhancement for the eslint-plugin-jest to support recognition and linting of custom test function names in a manner similar to the default describe and test functions. The current configuration of the plugin assumes usage of the default test block functions, which might not cover scenarios where teams use custom function names to organize and structure their tests. e.g. If someone is using https://github.com/doctolib/jest-os-detection/tree/master for running OS specific test in CI

**Feature Description:**
The suggested enhancement aims to extend the capabilities of eslint-plugin-jest to allow users to specify custom function names that serve the same purpose as the standard describe and test functions. This would ensure that linting rules are consistently applied to these custom test blocks, improving code quality and test organization.

**Proposed Solution:**
The proposed solution involves introducing a configuration option within the plugin that allows users to specify custom describe and test block names. These custom function names would be treated by the plugin as equivalent to the standard describe and test functions, enabling seamless linting for all types of test blocks.

**Benefits:**

**Flexibility:** Teams often adopt their own conventions for test function names to match their project's requirements. This feature would cater to this diversity and offer greater flexibility in organizing tests.

**Improved Code Quality:** Consistent linting across custom test blocks would ensure that best practices and coding standards are maintained, contributing to higher code quality.

Enhanced Usability: The feature would simplify the process of integrating custom test function names with existing linting configurations, reducing the need for workarounds or manual adjustments.

Implementation Considerations:

Ensure backward compatibility with existing configurations that rely on the default describe and test function names.

Provide clear documentation on how to configure and use the custom function recognition feature.

Consider potential performance implications, ensuring that the additional feature doesn't negatively impact linting performance.

**Comment by G-Rath** [comment]
[We already support this](https://github.com/jest-community/eslint-plugin-jest#aliased-jest-globals), though iirc it won't work with `it.onMac` etc. The potential problem with supporting that is the order of the submethods is not consistent and sometimes we depend on counts i.e it's `expect().not.resolve` not `expect().resolve.not`, and so we have logic saying "if the first submethod is `not` then the second _must_ be either `resolve` or `reject`".

That's not to say it's impossible, but I wouldn't be surprised if it requires a lot of threading to pass the context you'd need down to the internals.

As a workaround, you should be able to assign those to a method/variable and then use that in the settings for `eslint-plugin-jest`:

```
const describeOnMac = describe.onMac
```

**Comment by g-tiwari** [comment]
Hey, 
can you help me with an example for this ?, 
I have added custom aliases in eslint, but then those are not recognised by typescript in my test code

**Comment by G-Rath** [comment]
Here's a rough example with `context`:

```
// .eslintrc.js
module.exports = {
  parser: '@typescript-eslint/parser',
  plugins: ['eslint-plugin-jest'],
  settings: {
    jest: {
      globalAliases: {
        describe: ['context'],
      }
    }
  },
  overrides: [
    {
      files: ['test/**'],
      plugins: ['jest'],
      extends: ['plugin:jest/recommended']
    }
  ]
};

// jest.config.ts
import { Config } from '@jest/types';
import 'ts-jest';

const config: Config.InitialOptions = {
  setupFilesAfterEnv: [
    './test/setup.ts'
  ],

  transform: {
    [/\.tsx?/u.source]: ['ts-jest']
  }
};

export default config;

// test/setup.ts
global.context = describe;

declare var context: jest.Describe;

// test/add.test.ts
import { add } from '../add';

describe('#add', () => {
  context('when the numbers are the same', done => {
    it('equals the same as n * 2', () => {
      expect(add(1, 1)).toBe(1 * 2);
    });
  });
});
```

```
❯ npx eslint . --ext ts

/home/jones/workspace/projects-scrap/jest-example/test/add.test.ts
  4:45  error  Unexpected argument(s) in describe callback  jest/valid-describe-callback

✖ 1 problem (1 error, 0 warnings)
```
