### ISSUE TITLE
`no-focused-tests` should highlight only `fit` and `fdescribe` instead of the whole thing

### ISSUE THREAD

**Issue by pvinis** [jest-community/eslint-plugin-jest#1439]
When I use this rule, which is recommended also, while I fix a test, I usually do `fit` while I fix it so the whole file doesnt have to run.

Ideally, this rule should stop me from committing with the `fit` still. But when it makes the whole test red, its really hard to read and fix a test.

This rule should red-highlight the `fit` part of `fit("checks something", () => {`, not the whole thing.

**Comment by G-Rath** [comment]
That's up to your IDE, not us - we report a single node in the AST; see #958, #641, and #539

**Comment by pvinis** [comment]
I am making a PR to fix this. It's not the IDE's fault. I'll be back with a PR 🤞.

**Comment by pvinis** [comment]
(quick question, do you already have a "playground" of sorts on this repo, so we can play around with rules and actual tests?)

**Comment by G-Rath** [comment]
Actually, it is the IDEs fault - that is what handles rendering the ranges; the role of an eslint plugin is to report things against nodes and ranges which should be as accurate as possible and in this case we're decided that the call expression is the problem.

In this case I actually think that it could be understandable to report on the identifier instead as arguably that is what the rule technically cares about, but my bigger problem is that another IDE could decide to render that differently and I don't want to have to think about every single IDE when deciding what node we should report on.
