### ISSUE TITLE
Is `environments.globals` misconfigured?

### ISSUE THREAD

**Issue by fisker** [jest-community/eslint-plugin-jest#1515]
https://github.com/jest-community/eslint-plugin-jest/blob/a5ca480b53369461f92ae9b54b8d13154dc00db1/src/index.ts#L97-L99

Shouldn't it be 

```diff
    globals: {
-      globals,
+      jest: globals,
    },
```

?

**Comment by G-Rath** [comment]
It's been like that since before we converted to TypeScript (which was 2+ years ago), so I'm going to tentatively say "no" but maybe it's been broken all this time and not noticed 🤷‍♂️

Have you got any examples of it not working?

**Comment by fisker** [comment]
> Have you got any examples of it not working?

I don't. I guess "jest: true" works because eslint have `jest` globals https://github.com/eslint/eslintrc/blob/4151865b09084369e89d591eb2e01b9617287982/conf/environments.js#L170, and the date is from `globals` package, and I changed it to use data from here just now... https://github.com/sindresorhus/globals/pull/235

**Comment by fisker** [comment]
> which was 2+ years ago

I found it's like this 5 years ago, https://github.com/jest-community/eslint-plugin-jest/commit/e81cf69983dbea7130bf1f4865eee3299aa8f792#diff-bfe9874d239014961b1ae4e89875a6155667db834a410aaaa2ebe3cf89820556L15

**Comment by fisker** [comment]
@mdjermanovic Maybe you know how should it be defined?

**Comment by G-Rath** [comment]
Fwiw @SimenB has talked previously about ditching those globals since we now resolve them using a utility which has a complete definition of all Jest functions and their possible chains

**Comment by G-Rath** [comment]
I'm on mobile so it's hard to quote but checkout this: https://eslint.org/docs/latest/extend/plugins#environments-in-plugins

From what I understand from that, what we are doing is correct (this is fresh in my head too as I checked a few days ago when I was this as part of doing the flat config support)

**Comment by fisker** [comment]
From what I can see from the link, it should be

```diff
  environments: {
-    global: {
+    jest: {
      globals,
    },
  },
```

Example in the docs

```js
module.exports = {
    environments: {
        jquery: {
            globals: {
                $: false
            }
        }
    }
};
```

**Comment by G-Rath** [comment]
> To use the environment in ESLint, you would use the unprefixed plugin name, followed by a slash, followed by the environment name. So if this plugin were named eslint-plugin-myplugin, then you would set the environment in your configuration to be "myplugin/jquery"

Hence, `jest/globals` since our plugin is `eslint-plugin-jest` and our globals are called `globals`

**Comment by fisker** [comment]
Maybe you are right... It's confusing.

**Comment by fisker** [comment]
People are using `jest: true` 😄 

`jest: true` 147k files
https://github.com/search?q=jest%3A+true&type=code

`jest/globals: true` 702 files

https://github.com/search?q=jest%2Fglobals%3A+true&type=code

**Comment by fisker** [comment]
Never mind, it's legacy feature now.

**Comment by fisker** [comment]
Manually config in eslint.config.js

```js
   languageOptions: {
      globals: eslintPluginJest.environments.globals.globals, // <-- 
    },
```

https://github.com/prettier/prettier/pull/16105/files

**Comment by SimenB** [comment]
> People are using `jest: true` 😄
> 
> `jest: true` 147k files [github.com/search?q=jest%3A+true&type=code](https://github.com/search?q=jest%3A+true&type=code)
> 
> `jest/globals: true` 702 files
> 
> [github.com/search?q=jest%2Fglobals%3A+true&type=code](https://github.com/search?q=jest%2Fglobals%3A+true&type=code)

Yeah - the reason why we export our own (and encourage that) is that the built in version has Jasmine globals such as `fail`, `pending` etc which are not officially supported
