### ISSUE TITLE
Ensure toThrow always has a message

### ISSUE THREAD

**Issue by garyking** [jest-community/eslint-plugin-jest#154]
Consider adding a new rule, which checks that `toThrow` always has one argument, to match the error's message. 

This would have helped me a few times, when I used `toThrow` without any arguments, and it caught a general `TypeError`, etc. when instead I wanted it to catch a specific custom error.

**Comment by SimenB** [comment]
Yeah, that makes sense! PR welcome 🙂

**Comment by macklinu** [comment]
As per [the docs](https://jestjs.io/docs/en/expect#tothrowerror), would also want to check that the `toThrowError()` alias is checked as part of this rule too.
