### ISSUE TITLE
eslint v9 has just been released and support for v9 would be greatly appreciated

### ISSUE THREAD

**Issue by doberkofler** [jest-community/eslint-plugin-jest#1546]

**Comment by G-Rath** [comment]
Could you expand on what support is missing besides the version range? We've already got flat-config compatible configs.

**Comment by doberkofler** [comment]
I have already switched to the flat-config in v8 and it seems to work as expected, so as far as I'm aware it's only the version range.

**Comment by G-Rath** [comment]
Resolved by #1549
