### ISSUE TITLE
Lastest version 28.5 depends on @typescript-eslint/utils which has a peer dependency for "eslint": "^8.56.0" 

### ISSUE THREAD

**Issue by gdholly** [jest-community/eslint-plugin-jest#1588]
When running with eslint 7 we get the following:

Oops! Something went wrong! :(

ESLint: 7.32.0

Error: Failed to load plugin 'jest' declared in '.eslintrc.js': Cannot find module 'eslint/use-at-your-own-risk'
Require stack:
- .../node_modules/eslint-plugin-jest/node_modules/@typescript-eslint/utils/dist/ts-eslint/eslint/LegacyESLint.js
- ...node_modules/eslint-plugin-jest/node_modules/@typescript-eslint/utils/dist/ts-eslint/ESLint.js
- ../node_modules/eslint-plugin-jest/node_modules/@typescript-eslint/utils/dist/ts-eslint/index.js

**Comment by G-Rath** [comment]
Please provide a proper reproduction - we have an optional peer dependency on `@typescript-eslint/eslint-plugin` so its not being pulled in by us

**Comment by SimenB** [comment]
It's the utils in the stacktrace tho, not the eslint plugin. Not sure why that is hoisted 🤔 We'd need a full reproduction like Gareth mentions to properly investigate 👍

**Comment by gdholly** [comment]
Thanks for taking a look so quickly guys, here is the full stack trace.

> eslint src


Oops! Something went wrong! :(

ESLint: 7.32.0

Error: Failed to load plugin 'jest' declared in '.eslintrc.js': Cannot find module 'eslint/use-at-your-own-risk'
Require stack:
- ../../node_modules/eslint-plugin-jest/node_modules/@typescript-eslint/utils/dist/ts-eslint/eslint/LegacyESLint.js
- ../../node_modules/eslint-plugin-jest/node_modules/@typescript-eslint/utils/dist/ts-eslint/ESLint.js
- ../../node_modules/eslint-plugin-jest/node_modules/@typescript-eslint/utils/dist/ts-eslint/index.js
- ../../node_modules/eslint-plugin-jest/node_modules/@typescript-eslint/utils/dist/index.js
- ../../node_modules/eslint-plugin-jest/lib/rules/consistent-test-it.js
- ../../node_modules/eslint-plugin-jest/lib/index.js
- ../../node_modules/@eslint/eslintrc/lib/config-array-factory.js
- ../../node_modules/@eslint/eslintrc/lib/index.js
- ../../node_modules/eslint/lib/cli-engine/cli-engine.js
- ../../node_modules/eslint/lib/eslint/eslint.js
- ../../node_modules/eslint/lib/eslint/index.js
- ../../node_modules/eslint/lib/cli.js
- ../../node_modules/eslint/bin/eslint.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1142:15)
    at Module._load (node:internal/modules/cjs/loader:983:27)
    at Module.require (node:internal/modules/cjs/loader:1230:19)
    at require (../../node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (../../node_modules/eslint-plugin-jest/node_modules/@typescript-eslint/utils/dist/ts-eslint/eslint/LegacyESLint.js:5:32)
    at Module._compile (../../node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1426:10)
    at Module.load (node:internal/modules/cjs/loader:1205:32)
    at Module._load (node:internal/modules/cjs/loader:1021:12)
    at Module.require (node:internal/modules/cjs/loader:1230:19)

**Comment by SimenB** [comment]
Can you provide a separate repository with a minimal reproduction? Just remove everything you can while still getting the same error.

**Comment by gdholly** [comment]
Looks like this is caused by some other packages having a dependency to eslint 8.0+ which npm can't seem to detect. Thanks for your help.

**Comment by rpearce** [comment]
@gdholly What did you do to fix this? Did you identify the packages? I'm having the same issue after this minor upgrade.

**Comment by gdholly** [comment]
In our case I think there was a defect in npm that was hiding the true issue. We have set it aside until we upgrade eslint. Try to do what @SimenB suggested and build a repo from scratch with just your package.json and your eslint config file, there might be another package that is pulling in eslint 8+.

**Comment by rpearce** [comment]
Thanks for getting back to me! Our issue turned out to be that we were still on `eslint@6`, and upgrading to `8.x` resolved it.
