### ISSUE TITLE
Support `@typescript-eslint/utils` v8

### ISSUE THREAD

**Issue by ihorbond** [jest-community/eslint-plugin-jest#1633]
When this plugin is installed side by side with eslint v9 I get warnings in console:
![image](https://github.com/user-attachments/assets/6a13f5c3-1c18-44a0-a33b-ca7d7c7f3cda)
I assume because of https://github.com/typescript-eslint/typescript-eslint/blob/main/package.json#L138 ?

My package.json:
```
"dependencies": {
		"@markit/api": "^4.4.1",
		"@markit/api-errors": "^1.1.0",
		"@markit/config": "^1.2.4",
		"axios": "^1.7.2",
		"http-status-codes": "^2.3.0",
		"lodash": "^4.17.21"
	},
	"devDependencies": {
		"@markit/dcl-testsuite": "^0.7.0",
		"@markit/eslint-config-markit": "^2.0.0",
		"@markit/express-swagger-spec-tools": "^3.3.1",
		"cross-env": "^7.0.3",
		"eslint": "^9.8.0",
		"eslint-plugin-jest": "^28.6.0",
		"jest": "^29.5.0",
		"jest-junit": "^16.0.0",
		"swagger-tools": "^0.10.4"
	},
```

**Comment by vrhpires** [comment]
More specifically related with this:
https://github.com/jest-community/eslint-plugin-jest/blob/main/package.json#L61

The package `@typescript-eslint/utils` is expected to release a version 8 tomorrow (31-07-2024) with full support for ESLint 9:
https://github.com/typescript-eslint/typescript-eslint/discussions/8766

The dependency should also allow the major version 8:
`"@typescript-eslint/utils": "^6.0.0 || ^7.0.0 || ^8.0.0"`

**Comment by nikolay** [comment]
@vrhpires It got released, but the PR here is pinned to an alpha version.

**Comment by G-Rath** [comment]
thanks all - I plan to work on this over the next couple of weeks
