### ISSUE TITLE
Support for eslint 9.x.x

### ISSUE THREAD

**Issue by qoomon** [jest-community/eslint-plugin-jest#1641]
Any plans to support eslint version  9.x.x?

**Comment by G-Rath** [comment]
We already do

**Comment by FranciscoKloganB** [comment]
Would be nice if the documentation showed us on how to setup on Eslint 9.

There's only a link to Eslint documentation, but from my experience, Eslint Plugins are not being installed the same way on every package that made the jump to the newest version. A simple snippet would remove the guessing work.
