### ISSUE TITLE
[Feature]: Compatibility with the latest version of eslint

### ISSUE THREAD

**Issue by nayounsang** [jest-community/eslint-plugin-jest#1660]
Hello.
The contents of the docs are not compatible with the latest eslint version. I think it would be good to write about the latest eslint version for confusion.

**Comment by nayounsang** [comment]
This is temporary solution for my case.
```js
// eslint.config.mjs
import jestPlugin from "eslint-plugin-jest";

// ...

  {
    files: ["**/*.spec.{js,ts}"],
    plugins: {
      jest: jestPlugin,
    },
    languageOptions: {
      globals: {
        describe: "readonly",
        it: "readonly",
        test: "readonly",
        expect: "readonly",
        beforeEach: "readonly",
        afterEach: "readonly",
        beforeAll: "readonly",
        afterAll: "readonly",
        jest: "readonly",
      },
    },
    rules: {
      ...jestPlugin.configs["flat/recommended"].rules,
    },
  },

// ...

```

**Comment by G-Rath** [comment]
While the start of our readme only mentions `.eslintrc`, we do have documentation for flat config, including a full example under the ["Running rules only on test-related files" section of the readme](https://github.com/jest-community/eslint-plugin-jest?tab=readme-ov-file#running-rules-only-on-test-related-files), along with more examples in the ["Shareable configurations" section](https://github.com/jest-community/eslint-plugin-jest?tab=readme-ov-file#shareable-configurations).

From what I can tell just about all of our documentation especially at the start is pretty agnostic to the config format being used - probably the main one that isn't that might be worth updating is the first part of the "Usage" section, but I think the [ESLint docs on configuring plugins](https://eslint.org/docs/latest/use/configure/plugins) should make it pretty obvious what you need to do for that in flat config.

**Comment by mayronH** [comment]
@nayounsang I think the most basic config is just:

```js
// eslint.config.mjs

import pluginJs from '@eslint/js'
import pluginJest from 'eslint-plugin-jest'
import globals from 'globals'

export default [
  { files: ['**/*.js'], languageOptions: { sourceType: 'commonjs' } },
  { languageOptions: { globals: globals.browser } },
  pluginJs.configs.recommended,

  pluginJest.configs['flat/recommended'],
]

```
