### ISSUE TITLE
Missing dependency on typescript

### ISSUE THREAD

**Issue by aqeelat** [jest-community/eslint-plugin-jest#1687]
After installing eslint-plugin-jest, yarn is reporting:
`p99bfd → ✘ eslint-plugin-jest@npm:28.9.0 [d12f2] doesn't provide typescript to @typescript-eslint/utils@npm:8.18.1 [ebbdd] and 2 other dependencies`

**Comment by G-Rath** [comment]
Duplicate of #1117 - https://github.com/typescript-eslint/typescript-eslint/issues/10383 is likely going to address this
