### ISSUE TITLE
Padding between it and describe blocks.

### ISSUE THREAD

**Issue by hally9k** [jest-community/eslint-plugin-jest#17]
I have been looking for a rule to enforce padding around all `it` and `describe` blocks. Is this the correct place for that? Maybe `jest/padding-it-blocks` and `jest/padding-describe-blocks` rules?

```
it('My awesome test.', () => {
  expect(true).toBe(true)
})
// Enforcing this line of padding between the it blocks below this comment...

it('My other awesome test.', () => {
  expect(false).toBe(false)
})
```

**Comment by thymikee** [comment]
I'm not sure if we want to add any styling preferences.

**Comment by SimenB** [comment]
I agree that styling at this level is not something we want. `it` vs `test` is also styling, but makes more sense (#12).

@hally9k would https://eslint.org/docs/rules/padded-blocks work for you?

**Comment by SimenB** [comment]
Closing as we won't be adding it.

If you create a plugin for it, we could link to it 🙂

**Comment by dangreenisrael** [comment]
Hey @SimenB. We we looking for this functionality, and following your advice I created a plugin for it.  Any chance you would be willing to link to it?

Also, any feedback in general?

https://github.com/dangreenisrael/eslint-plugin-jest-formatting
https://www.npmjs.com/package/eslint-plugin-jest-formatting

**Comment by SimenB** [comment]
Cool! Please send a PR adding a link to it in our readme :) A PR to awesome-jest as well would be cool
