### ISSUE TITLE
typo in latest release notes

### ISSUE THREAD

**Issue by lukeapage** [jest-community/eslint-plugin-jest#196]
https://github.com/jest-community/eslint-plugin-jest/releases/tag/v21.27.0

the links are `eslint-plugin-jes/` instead of `eslint-plugin-jest/`

**Comment by SimenB** [comment]
That's a bug in semantic-release, mins opening up an issue there?

**Comment by lukeapage** [comment]
Sorry I’ve never used semantic release, I don’t know how it’s configured or if you need to update or.. something else so I’d feel uncomfortable raising an issue that just pointed at this one..

**Comment by lukeapage** [comment]
I can’t see the bug raised already with them

**Comment by G-Rath** [comment]
@SimenB did you ever end up opening up an issue for this?

**Comment by SimenB** [comment]
Ergh, I don't think so
