### ISSUE TITLE
Support ESLint's --fix-type option

### ISSUE THREAD

**Issue by macklinu** [jest-community/eslint-plugin-jest#202]
ESLint v5.9.0 introduced the [`--fix-type`](https://eslint.org/blog/2018/11/eslint-v5.9.0-released#the-fix-type-option) flag, which allows for people to fix issues of a certain type.

![image](https://user-images.githubusercontent.com/2344137/48282772-76963d00-e40f-11e8-8fe8-d377cba287bb.png)

To support this feature, we will want to update our fixable rules to use a `meta.type` property that is one of `problem`, `suggestion`, or `layout`.

**Comment by SimenB** [comment]
Whenever someone gets to this, make sure to enable https://github.com/not-an-aardvark/eslint-plugin-eslint-plugin/blob/master/docs/rules/require-meta-type.md as well

**Comment by SimenB** [comment]
The typescript utils require this to be defined, so this'll be fixed by completing the migration tracked in #256
