### ISSUE TITLE
New rule proposal: disallow large snapshots (no-large-snapshots)

### ISSUE THREAD

**Issue by anescobar1991** [jest-community/eslint-plugin-jest#21]
Hey all,

I've written a rule that I think would benefit the greater Jest community.

`no-large-snapshots` looks at all Jest snapshot files (files with `.snap` extension) and validates that each stored snapshot within those files does not exceed a certain number of lines (by default 35, though this is configurable and I am more than willing to change the default as is seen fit).

The reasoning for the rule is that as a matter of best practice snapshots should be limited in size in order to be more manageable and reviewable. A stored snapshot is only as good as its review and as such keeping it short, sweet, and readable is very important in my mind.

I already wrote the rule (and tests and docs) and it is being used internally by my team so if I was to open a PR to add it to `eslint-plugin-jest` would you consider it?

**Comment by thymikee** [comment]
I'm good with adding that, seems like a nice-to-have. Although I'd switch it off by default or increase the default value as it would be too painful 😄

**Comment by anescobar1991** [comment]
Great will open PR!

**Comment by SimenB** [comment]
Fixed in #24, released in 21.4.0. Thanks!
