### ISSUE TITLE
Question: use with TypeScript / tslint

### ISSUE THREAD

**Issue by lonix1** [jest-community/eslint-plugin-jest#215]
Has anyone figured out how to make this work with tslint (TypeScript)?

**Comment by SimenB** [comment]
I highly doubt it'll work with tslint. However, as TypeScript is moving to eslint, you should go that route: https://eslint.org/blog/2019/01/future-typescript-eslint

**Comment by lonix1** [comment]
Thanks for that tip, looks interesting!
