### ISSUE TITLE
Proposal: Rules Table

### ISSUE THREAD

**Issue by xfumihiro** [jest-community/eslint-plugin-jest#22]
Would be nice if we have a table like [this](https://github.com/pke/eslint-plugin-redux-saga):

![screen shot 2017-11-28 at 11 28 55 am](https://user-images.githubusercontent.com/12194969/33301188-5a68c0a8-d42f-11e7-89ac-36d58205583b.png)

**Comment by SimenB** [comment]
Ooooh, I like it. Wanna send a PR for it? 🙂

**Comment by xfumihiro** [comment]
Happy to!
