### ISSUE TITLE
semantic-release should be dev dependency

### ISSUE THREAD

**Issue by vhenzl** [jest-community/eslint-plugin-jest#220]
`semantic-release` and `@semantic-release/*` dependencies added in 13b7c987fcf1e96bdb3ec4de0c41127052a6992b should IMO go to `devDependencies`.

**Comment by SimenB** [comment]
They've dropped support for node 6, and I'd rather mess up there at times than risk breaking install for Node 6 without knowing it by disabling some engine check.

Thanks for the suggestion, though!

**Comment by vhenzl** [comment]
Well… I don't understand much what it's about, but I don't like `eslint-plugin-jest` now installs hundreds of dependencies including `npm` which doesn't seem to have any relation to this plugin's functionality.

**Comment by SimenB** [comment]
Oh wait, it added them to the release 😱 That's _not_ on purpose!
