### ISSUE TITLE
New rule: no istanbul ignore without reason

### ISSUE THREAD

**Issue by eranshabi** [jest-community/eslint-plugin-jest#222]
When using the `coverageThreshold` option of jest you sometimes you have to add `/* istanbul ignore next */` comments in order for your coverage to much the threshold.
Often people will add this comment with no reason of why the code is not covered (examples: covered in e2e, can't be covered, will be covered later...).
I think the reason why it's uncovered should be documented so other developers will know how to handle this code in the future, and that's why this rule would be useful.

What do you think? Is it related enough to jest to be here?

**Comment by SimenB** [comment]
Good idea!

>What do you think? Is it related enough to jest to be here?

I'd think so - quick googling didn't yield any istanbul plugin.

/cc @bcoe thoughts?

**Comment by antonk52** [comment]
Are there any more thoughts on this topic? This looks like a healthy feature to go along with a linter rule to enforce it

**Comment by SimenB** [comment]
Agreed, would be nice to get this in. Wanna provide a PR? 😀 Ideally this would be in some sort of `eslint-plugin-istanbul`, but as far as I can tell that doesn't exist. Istanbul backs all of JS code coverage (via `nyc` or `c8` (as well as Jest, of course)), and such a rule seems useful for all

**Comment by antonk52** [comment]
I am happy to put a PR together, any advice on the rule setting, I have in mind two rules to implement:
- `prefer-istanbul-ignore-description`
  essentially errors/warns on any "Istanbul ignore" comment without a specified comment.
- `no-istanbul-ignore-file`
  errors for any mention of `Istanbul ignore file` comment. 

What do you think? Should there be any custom settings for the proposed rules?

**Comment by SimenB** [comment]
Those sounds good to me! No options come to mind 🙂

**Comment by SimenB** [comment]
We should link to `eslint-plugin-istanbul` from our README
