### ISSUE TITLE
New rule request: no-empty-title

### ISSUE THREAD

**Issue by dashmug** [jest-community/eslint-plugin-jest#226]
Having an empty string as title is useless. Can we have a rule that prevents this?

**Comment by SimenB** [comment]
Yeah, for sure! Should be pretty straight forward. Wanna send a PR?

**Comment by dashmug** [comment]
Thanks for confirming that the rule doesn't exist yet.

I'm very busy at the moment but I'll see if I can do this during the weekend.

**Comment by dashmug** [comment]
To anyone who's interested, feel free to make a PR. I'll try doing it myself but currently not finding the time to do so (I have not written an `eslint` rule before).
