### ISSUE TITLE
jest/no-identical-title error in abstracted describe

### ISSUE THREAD

**Issue by donovanhiland** [jest-community/eslint-plugin-jest#229]
Working on a react native project and have some testing helpers like:

```
function onAndroid(testBlock) {
  describe('on Android', () => {
    const os = Platform.OS
    beforeAll(() => {
      Platform.OS = 'android'
    })
    afterAll(() => {
      Platform.OS = os
    })

    testBlock()
  })
}

function onIOS(testBlock) {
  describe('on iOS', () => {
    const os = Platform.OS
    beforeAll(() => {
      Platform.OS = 'ios'
    })
    afterAll(() => {
      Platform.OS = os
    })

    testBlock()
  })
}
```

which triggers the `no-identical-title` rule in code like:

```
    describe('choosing an image', () => {
      onIOS(() => {
        it('works', () => {})
      })

      onAndroid(() => {
        it('works', () => {})
      })
    })
```

What would be the best way around this other than disabling that linting rule for those lines?

**Comment by SimenB** [comment]
I don't think we can statically know what the name will be, so I guess disabling the rule here is the only option?

**Comment by donovanhiland** [comment]
Thanks for the quick response! Is there a way I could structure my helpers so that it _could_ statically be known? This seems like a common use case that maybe I'm just doing it wrong.

If there's no better options, disabling the lint rule works for me 👍

**Comment by SimenB** [comment]
I don't think so - right now we just walk up all `describe`s above in the scope. Following wrapper scopes seems hard. Feel free to send a PR fixing the rule if you're able to, though!
