### ISSUE TITLE
Suggest toMatchObject over toEqual(expect.objectContaining)

### ISSUE THREAD

**Issue by garyking** [jest-community/eslint-plugin-jest#230]
If `expect().toEqual(expect.objectContaining)` is the same as `expect().toMatchObject()` then perhaps have a rule to suggest the latter instead?

**Comment by SimenB** [comment]
I wonder if we maybe want to go the other way? Would be nice to remove `toMatchObject` from Jest, as the asymmetric matcher provides the needed primitive?

/cc @thymikee

**Comment by thymikee** [comment]
It's more writing though, I'm not sure if people would like it. We could start with something like `prefer-object-containing` though

**Comment by rdsedmundo** [comment]
Those matchers from time to time lead me into confusion with respect to each one to use, the differences between both, etc.

And it's not just me (20k views): https://stackoverflow.com/questions/45692456/whats-the-difference-between-tomatchobject-and-objectcontaining

**Comment by garyking** [comment]
@rdsedmundo Yes I absolutely agree. That's why I wrote a rule for myself, for the moment, which prefers `objectContaining` over `toMatchObject`, with the reason being that the former is more strict.
