### ISSUE TITLE
New rule request: title-matches-pattern

### ISSUE THREAD

**Issue by dashmug** [jest-community/eslint-plugin-jest#233]
Some teams might want to have a convention for their test titles. A lint rule that can enforce this will be very useful.

Options can be added to further specify whether the rule applies to `describe`, `it`, or `test`.

**Comment by G-Rath** [comment]
Now that we have `valid-title`, I think it makes sense to support this as an option for that rule, rather than as a new rule; something like `mustMatch`, which takes a RegExp-as-a-string or an object of type `Record<'describe' | 'it' | 'test', string>`.
