### ISSUE TITLE
README does not answer the question "why?"

### ISSUE THREAD

**Issue by john-aws** [jest-community/eslint-plugin-jest#243]
The README documents how to install, use, and configure the plugin but it does not address the question of why we should do any of this.

Why should someone use this project? What does it do and what benefits will be gained?

**Comment by SimenB** [comment]
>Why should someone use this project? What does it do and what benefits will be gained?

Seems like a general "why use eslint" to me, which I don't think belong in this repo. Its purpose is the same as most other eslint plugins - to help you detect and fix errors and inconsistencies in your code base.
I'm not sure exactly what sort of text you're missing from the readme. Could you point to some example of another eslint plugin that answers the question "why"?
