### ISSUE TITLE
Add different setting for no-large-snapshots for inline vs external snaps

### ISSUE THREAD

**Issue by alexkrolick** [jest-community/eslint-plugin-jest#244]
It would be cool to be able to specify the max length of inline snapshots separately from snapshots in files.

Main use case is setting inlineSnapshots to be something like 15 lines max, but a larger number like 50 for  regular snapshots.

**Comment by SimenB** [comment]
Yeah, great idea! Wanna send a PR?

**Comment by alexkrolick** [comment]
Yes, I'll send one

**Comment by chrisblossom** [comment]
I was just about to put an issue requesting this feature in `prefer-inline-snapshots`.

**Comment by alexkrolick** [comment]
(still planning on doing this)

**Comment by leonardovillela** [comment]
Can I take this issue?

**Comment by SimenB** [comment]
Yeah, go for it 🙂
