### ISSUE TITLE
Option for `lowercase-name` rule to allow uppercase for top level describes

### ISSUE THREAD

**Issue by overlookmotel** [jest-community/eslint-plugin-jest#247]
My preferred style is for top-level `describe`/`it`s to have names starting with a capital letter, and all nested blocks lower case. So then the concatenated test name reads like a sentence starting with a capital letter.

e.g.:

```js
describe('Monkeys', () => {
  describe('eat', () => {
    it('bananas', () => { /* ... */ } );
  });

  it('sleep in the daytime', () => { /* ... */ } );
});

it('Elephants are very big', () => { /* ... */ } );

// Monkeys eat bananas
// Monkeys sleep in the daytime
// Elephants are very big
```

At present this style is not possible to enforce with the `lowercase-name` rule.

How about:

1. Add `lowercase-name` `ignore` options `'top-describe'`, `'top-it'`, `'top-test'` (and `'top'` as a shortcut for all three)
2. Add a new `uppercase-name` rule with the same options.

Alternatively, a new rule called e.g. `name-case` could cover all possible permutations, with options something like:

```js
"lower"
"upper"

// Override for different statements
"lower", { "describe": "upper", "it": "upper", "test": "upper" }
"upper", { "describe": "ignore" }

// Override for all top-level statements
"lower", { "top": "upper" }

// Override for specific top-level statements
"lower", { "describe": "upper", "top": { "describe": "lower" } }
```

Do you feel this would be useful?

**Comment by SimenB** [comment]
Happy to merge a PR with an `ignore` option added 🙂

**Comment by overlookmotel** [comment]
Great! What do you think about a new `name-case` rule which covers all possibilities?

**Comment by gayathrigs27** [comment]
I will take this up

**Comment by overlookmotel** [comment]
@gayathrigs27 Great!

Which variant are you planning to implement? My favoured one was a `name-case` rule as that covers all possibilities. I'm not sure if the maintainers would accept that though.

**Comment by gayathrigs27** [comment]
I thought of using the approach SimenB suggested
