### ISSUE TITLE
New rule: no-commented-out-tests

### ISSUE THREAD

**Issue by kangax** [jest-community/eslint-plugin-jest#261]
There's already a rule to catch disabled tests. In our codebase, I'm seeing cases where people disable tests by commenting them out. While this could be easily caught during code reviews, it'd be nice to disallow this via a rule before it even makes it to the review.

Implementation-wise, we could probably detect cases of `describe`/`it`/etc. within comments and warn then.

**Comment by SimenB** [comment]
I'm not sure if it's possible to detect this. Normally we just ask for `CallExpression`, but in a comment it's just a string. Wanna try to provide PR for it?

**Comment by jeysal** [comment]
Throwing some regexes at comment contents to catch common cases sounds fine to me if someone wants to take a shot at implementing this 😄

**Comment by kangax** [comment]
@SimenB @jeysal here you go — lemme know what you think
