### ISSUE TITLE
seeking advice on no-large-snapshots

### ISSUE THREAD

**Issue by benmonro** [jest-community/eslint-plugin-jest#281]
I'm working with a codebase that has a very large number of snapshots, a large majority of them are either gargantuan, very large, or large.  I'd like to add the no-large-snapshots rule, but I'd like to add them in a way that it applies to changes going forward.  In otherwords, is there a way to have disable the rule for the snapshots that currently fail, but have them proceed w/ new tests/snaps?

many thanks in advance.

**Comment by SimenB** [comment]
Not really, as far as I know. You can add the rule as `warning` level, and use [`--max-warnings`](https://eslint.org/docs/user-guide/command-line-interface#--max-warnings) set to the current level of warnings you get to ensure you do not regress? Might get noisy...

Another alternative might be to explicitly ignore the existing snapshots for the rule. This is a per-file thing, though

**Comment by benmonro** [comment]
Yeah sadly neither of those options would work.  There's a ton of files.  I tried using disable comments but those get wiped out when you do -u

**Comment by SimenB** [comment]
I meant to use `overrides` in eslint config, not individual disable comments

**Comment by benmonro** [comment]
@SimenB is this possible / feasible to implement in the rule? https://github.com/facebook/jest/issues/8579#issuecomment-503278185

it would be very beneficial if we could disable the rule in this way.

**Comment by benmonro** [comment]
@SimenB trying to implement this in my fork but a bit stuck.  Looking for a way to have a snapshot resolver that just uses the jest config configured for the project. any chance you've pulled in the jest config for a project into a lint rule for jest before?

**Comment by benmonro** [comment]
@SimenB implemented on this PR: https://github.com/jest-community/eslint-plugin-jest/pull/282
