### ISSUE TITLE
How to apply "jest/globals" to "jest-dom/extend-expect"

### ISSUE THREAD

**Issue by skywickenden** [jest-community/eslint-plugin-jest#289]
If I import extended expect functions such as `toContainElement`

    import { toContainElement } from "jest-dom/extend-expect";

I get a lint error:

  3:10  error  'toContainElement' is defined but never used  no-unused-vars

toContainElement is used as an extension to expect, eg: 

     expect(foo).toContainElement(bar);  

Is it possible to fix this without resorting to `// eslint-disable-line no-unused-vars`

My `eslintrc.js`:

    module.exports = {
        "env": {
            "browser": true,
            "es6": true,
            "jest/globals": true,
        },
        "extends": "eslint:recommended",
        "globals": {
            "Atomics": "readonly",
            "SharedArrayBuffer": "readonly"
        },
        "parserOptions": {
            "ecmaFeatures": {
                "jsx": true
            },
            "ecmaVersion": 2018,
            "sourceType": "module"
        },
        "plugins": [
            "react",
            "jest",
        ],
        "rules": {
            "react/jsx-uses-react": "error",
            "react/jsx-uses-vars": "error",
            "indent": [
                "error",
                2
            ],
            "linebreak-style": [
                "error",
                "windows"
            ],
            "quotes": [
                "error",
                "double"
            ],
            "semi": [
                "error",
                "always"
            ]
        }
    };

**Comment by SimenB** [comment]
`no-unused-vars` is an eslint core rule, it doesn't come from this plugin. `jest/globals` just adds `expect`, `describe`, `test` etc, not matchers.

This question is better asked on StackOverflow as its relation to this plugin is orthogonal to it
