### ISSUE TITLE
rename require-tothrow-message to require-to-throw-message

### ISSUE THREAD

**Issue by chrisblossom** [jest-community/eslint-plugin-jest#296]
Would a PR be accepted that would rename `require-tothrow-message` to `require-to-throw-message`? `tothrow` is not a word and for those of us using a spell checker in our IDE (webstorm / vscode plugin) it is distracting.

I think the PR would not remove `require-tothrow-message`, but rename all instances of it and possibly deprecate the old name.

**Comment by jeysal** [comment]
I'm worried that it would be less clear that it refers to the `toThrow` matcher.
Questions upon reading the rule name might be:
Where does it "require to throw [a] message"? Why would I throw a message?

**Comment by chrisblossom** [comment]
Interesting, when I read it originally on the readme, I assumed it was a spelling mistake and wasn't didn't know exactly what it was referring to until I read the description. Which I could have interpreted it the same as you said as is.

I personally don't think that should/would be an issue, but it could be renamed to something like:

- `to-throw-require-message`
- `require-message-in-to-throw`

Also, this is inconsistent with other rules (that same concern should apply here too), see

| current style            | `tothrow` style        |
|--------------------------|------------------------|
| `prefer-to-have-length`  | `prefer-tohavelength`  |
| `prefer-to-contain`      | `prefer-tocontain`     |
| `prefer-to-be-undefined` | `prefer-tobeundefined` |
| `prefer-to-be-null`      | `prefer-tobenull`      |
| `prefer-strict-equal`    | `prefer-strictequal`   |
| `prefer-spy-on`          | `prefer-spyon`         |

I do not think the other rules should change. I think `require-tothrow-message` should be updated to match others.

**Comment by jeysal** [comment]
Oh I didn't have the names of those other rules in mind, looks like tothrow
is indeed the outlier. Not sure if the rename is important enough to
warrant the breaking change though

**Comment by chrisblossom** [comment]
> Not sure if the rename is important enough to warrant the breaking change though

I personally think it is.

**Comment by jeysal** [comment]
@simenb thoughts?
