### ISSUE TITLE
prefer-inline-snapshots max length

### ISSUE THREAD

**Issue by chrisblossom** [jest-community/eslint-plugin-jest#297]
I'd like to see an option for `prefer-inline-snapshots` that would only recommend inline snapshots that are under X lines long.

**Comment by jeysal** [comment]
Sounds like a good idea, although given the difficulties encountered in https://github.com/jest-community/eslint-plugin-jest/pull/282, unless those are solved it would mean the rule would need to be changed to report errors in the snap file :|

**Comment by alexkrolick** [comment]
Dupe of #244

**Comment by jeysal** [comment]
true
