### ISSUE TITLE
Add a changelog

### ISSUE THREAD

**Issue by SimenB** [jest-community/eslint-plugin-jest#3]
Should we go for semantic commits so we don't have to manually maintain it?

Should we use semantic release and just publish from CI?

**Comment by thymikee** [comment]
I’ve tried semantic-release once and had some issues back then. But maybe we could revisit

**Comment by orta** [comment]
I'm always optimistic towards semantic-release for smaller libs, so maybe it's worth a try - yeah

**Comment by SimenB** [comment]
@orta could you set up danger here?

**Comment by ai** [comment]
I found 21.3 release and it was hard to find what feature was added

**Comment by SimenB** [comment]
Also see https://github.com/jest-community/eslint-plugin-jest/releases
