### ISSUE TITLE
[new rule] no-vague-titles

### ISSUE THREAD

**Issue by cartogram** [jest-community/eslint-plugin-jest#313]
At Shopify, we have a [rule that prevents specific words](https://github.com/Shopify/eslint-plugin-shopify/blob/master/docs/rules/jest/no-vague-titles.md) from test titles. This is pretty nuanced/ specific, but I'd love to add it to this repo.

**Comment by suganya-sangith** [comment]
@cartogram  I have recently added a PR for valid-title rule, you could incorporate this case to the same rule.

**Comment by DimaDK24** [comment]
Will be cool if this is added to the `valid-title` rule or added as a new rule :)

**Comment by G-Rath** [comment]
@DimaDK24 I'll look at adding this on the weekend :)
