### ISSUE TITLE
valid-describe should support describe.each

### ISSUE THREAD

**Issue by G-Rath** [jest-community/eslint-plugin-jest#336]
As per #334, `valid-describe` currently doesn't support `describe.each`, instead just bailing out.

**Comment by G-Rath** [comment]
I'm wondering if this should be a separate rule? (`valid-describe-each`).

Just b/c the domains are nicely encapsulated - otherwise `valid-describe` is going to get pretty bloated & strung out.

**Comment by SimenB** [comment]
I think conceptually it doesn't make sense to separate them, even though the implementation might be a bit big. But branching inside of it into what's essentially to separate rules can work? Without increasing implementation complexity

**Comment by SimenB** [comment]
It doesn't bail out anymore, it has false positives

**Comment by G-Rath** [comment]
Yeah huh I thought I closed this already 🤷‍♀

**Comment by SimenB** [comment]
False positives is _worse_ than bailing 😛

**Comment by G-Rath** [comment]
> False positives is worse than bailing 😛

Well then make an issue 😜 

I thought I fixed all the false positives?
