### ISSUE TITLE
TypeScript dependency?

### ISSUE THREAD

**Issue by topaxi** [jest-community/eslint-plugin-jest#339]
Does this plugin need typescript installed? There is no mention in the README, yet our setup crashes with `Cannot find module 'typescript'` once we installed this plugin.

**Comment by aknorw** [comment]
I have the same issue, described here: https://github.com/jest-community/eslint-plugin-jest/issues/338#issuecomment-513820554

**Comment by duncan-thacker** [comment]
Same problem here, using a non-typescript project. I get 

Error: Failed to load plugin 'jest' declared in '.eslintrc.json': Cannot find module 'typescript'

> Referenced from: ...\demo-loader\.eslintrc.json
>     at Function.Module._resolveFilename (module.js:538:15)
>     at Function.Module._load (module.js:468:25)
>     at Module.require (module.js:587:17)
>     at require (...\demo-loader\node_modules\v8-compile-cache\v8-compile-cache.js:161:20)
>     at Object.<anonymous> (...\demo-loader\node_modules\@typescript-eslint\typescript-estree\dist\parser.js:17:25)
>     at Module._compile (...\demo-loader\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
>     at Object.Module._extensions..js (module.js:654:10)
>     at Module.load (module.js:556:32)
>     at tryModuleLoad (module.js:499:12)
>     at Function.Module._load (module.js:491:3)

Reverting to 22.13.0 fixes the problem.

**Comment by SimenB** [comment]
Bah, I thought this was fixed (https://github.com/typescript-eslint/typescript-eslint/pull/584)... Should have verified manually, sorry! As a quickfix I'll add typescript as a dependency.

/cc @bradzacher

**Comment by bradzacher** [comment]
https://github.com/jest-community/eslint-plugin-jest/blob/d0a84286702afa794c2ff4b908b020d1a8b1ecbf/src/rules/valid-describe.ts#L1

VSCode's auto-import got you!

typescript will happily auto-import `@typescript-eslint/typescript-estree`, even if it's a transient dependency.
This would normally be fine, but `typescript-estree`'s `index.js` has a hard import on typescript.
typescript-eslint/typescript-eslint#584 worked around this by deeplinking past the entry point.

I'd suggest using the `import/no-extraneous-dependencies` rule, as it'll make sure that modules exist in `package.json`

**Comment by SimenB** [comment]
Yeah, I just noticed when trying to create a bug report for you 😅 Yup, I was gonna add that rule when I noticed the error. Thanks!

**Comment by SimenB** [comment]
Pushed 7f1867bd22374a05e163d1af2d24ece7d74ae74e

**Comment by pponugo** [comment]
Is this fix broken again? Looks like TypeScript is again required in version 27
