### ISSUE TITLE
Add support for spyOn() as a valid global

### ISSUE THREAD

**Issue by ecbrodie** [jest-community/eslint-plugin-jest#35]
I am trying to use the `spyOn()` method in my Jest tests. Although this is a valid global Jest function, it is still causing the following ESLint error:

```
error  'spyOn' is not defined
```

I have followed the instructions to setup this plugin, including installing it as a devDependency, adding "jest" to my eslintrc plugins and adding "jest/globals" to the `env` object. ESLint still throws an error. I even tried extending "plugin:jest/recommended", but that still throws the error.

What I find interesting is that there was a [past commit (2984eb50c)](https://github.com/jest-community/eslint-plugin-jest/commit/2984eb50cf7336e7b682888ad31a745ed8a232fd) that introduced support for `spyOn` as a valid global. However, there was soon after [another commit (491271aaa)](https://github.com/jest-community/eslint-plugin-jest/commit/491271aaa3a1313b2ddeb15608131951c2ad03e0) that reverted the previous one, so that support for `spyOn` was removed. I am curious to understand more about the intent of these commits. It seems like the former commit, which includes support for `spyOn` as a valid global, would fix my issue.

In the meanwhile, I am getting around this my adding a `/* global spyOn */` comment to each file that uses `spyOn()`. Ideally, this project can make ESLint smart enough to know that `spyOn` is a valid global method.

Thank you.

**Comment by thymikee** [comment]
Global `spyOn` is not Jest, it's a part of Jasmine. Use [`jest.spyOn()`](https://facebook.github.io/jest/docs/en/jest-object.html#jestspyonobject-methodname)

**Comment by GeorgeTaveras1231** [comment]
@thymikee since Jest supports the global `spyOn` it seems wrong for `eslint-plugin-jest` to not support it.

Unless theJjest developers want to deprecate the global `spyOn`, in which case, the warnings should be coming from jest, not from `eslint-plugin-jest` 🤔

**Comment by thymikee** [comment]
@SimenB wdyt?

**Comment by GeorgeTaveras1231** [comment]
I've also found that there are behavioral differences between `spyOn` and `jest.spyOn`.

In my test, I initially had:

```js
spyOn(window.location, 'assign')

/* Omitted */

expect(window.location.assign).toHaveBeenCalledWith('/some-path')
```

Which worked fine.


After changing it to use the `jest` global, it stopped working
```js
jest.spyOn(window.location, 'assign')

/* Omitted */

expect(window.location.assign).toHaveBeenCalledWith('/some-path')
```

This would yield the `JSDOM` error:

```
SyntaxError: Could not resolve the given string "/some-path" relative to the base URL "about:blank"
```

To fix this, I had to explicitly mock the implementation of the spy:

```js
jest.spyOn(window.location, 'assign').mockImplementation(() => {}) // < Call .mockImplementation

/* Omitted */

expect(window.location.assign).toHaveBeenCalledWith('/some-path')
```

### Conclusion
It seems like `spyOn` automatically mocks the implementation with a No-Op function, which allowed the original version of the test to work. 

Hopefully with this I've demonstrated that there may be use cases for the global `spyOn`. However, it is also hard to tell whether this difference was actually intended by the Jest developers.

**Comment by SimenB** [comment]
Using `spyOn`, `pending`, `fail` etc is not really supported.

That said, I'd be happy to have a rule saying "don't use jasmine globals", whilst adding this to our list of globals
