### ISSUE TITLE
Fix changelog generation

### ISSUE THREAD

**Issue by G-Rath** [jest-community/eslint-plugin-jest#361]
Currently our [CHANGELOG](https://github.com/jest-community/eslint-plugin-jest/blob/master/CHANGELOG.md) is very out of date, which makes people sad 😢 

It [should be being handable](https://github.com/jest-community/eslint-plugin-jest/commit/924daedc7bdc00a757bb534138bd4ca65b5a281f) by `@semantic-release/changelog`, but that [was reverted due to config issues](https://github.com/jest-community/eslint-plugin-jest/commit/d912a70286fa13dd65f121719c91ed21ca0da080) :/

Also see #214 & #360

**Comment by SimenB** [comment]
23 includes the changelog, but the updated one is not pushed back to the repo.

https://runpkg.com/?eslint-plugin-jest@23.0.0/CHANGELOG.md

so we need to both update the one in this repo and try to commit the changelog back from semantic-release
