### ISSUE TITLE
Include globals and 'jest' plugin in recommended

### ISSUE THREAD

**Issue by scriptdaemon** [jest-community/eslint-plugin-jest#37]
I propose that the following be added to the "recommended" config option:

```js
plugins: [
  'jest'
],
env: {
  'jest/globals': true
}
```

That way, when extending the recommended settings, a user does not have to include these manually. Both `eslint-config-standard` and `eslint-plugin-vue` (and probably others) do this as well. I'll submit the PR if this proposal is accepted.

**Comment by SimenB** [comment]
React plugin does it as well, so I'm +1. PR welcome 🙂
