### ISSUE TITLE
no-large-snapshots should not care about file types

### ISSUE THREAD

**Issue by G-Rath** [jest-community/eslint-plugin-jest#370]
Currently, `no-large-snapshots` checks if the file being linted ends w/ the `.js` file extension, preventing it from linting other files, such as `.tsx`, `.ts`, & `.jsx`.

This file check should be removed. 

https://github.com/jest-community/eslint-plugin-jest/blob/85e4195ecb9373befd42018a8fe4f4bb13cfa629/src/rules/no-large-snapshots.js#L88

**Comment by SimenB** [comment]
Potentially a breaking change, but I'd call it a bugfix... 

It was added in #186, @JohanBrorson thoughts on just removing the check? We should just `return` from the `.snap` `if`

**Comment by G-Rath** [comment]
I can confirm that it does mean `.ts` files won't be linted by this rule.

Aside from that, I wouldn't really call it "breaking" per say, for the same reason `prefer-to-spyon` shouldn't bother trying to figure out if it's in a test file: `eslint-plugin-jest` is only meant for jest tests suites.

**Comment by graphan** [comment]
@G-Rath, @SimenB, @JohanBrorson We have our tests written in TypeScript, so we need it to be fixed. I created the following PR: https://github.com/jest-community/eslint-plugin-jest/pull/581
It is not passing due to some reason though, could you take a look?
