### ISSUE TITLE
[valid-expect]: Make number of args allowed by a "valid" expect configurable

### ISSUE THREAD

**Issue by G-Rath** [jest-community/eslint-plugin-jest#391]
Currently we only consider an expect valid if it has a single argument - otherwise we report that it has multiple arguments and thus is invalid.

While this is true for vanilla jest, it's possible to modify expect to be valid w/ more than one argument, such as via [`jest-expect-message`](https://www.npmjs.com/package/jest-expect-message).

Hence, we should make this a configurable option.

**Comment by G-Rath** [comment]
I'll do this in a few hours when I'm off work :)

It'll just be something like "maxArgs" that takes a number.

@SimenB do you know of any other libraries that modify the number of arguments `expect` can take?

In particular, I'm interested in if there are any that add required arguments (I'd imagine not, but I've not explored the jest ecosystem much).

**Comment by SLiebald** [comment]
We stumbled over this issue when adding eslint-plugin-jest to our project.

As valid-expect has more useful check than just the "only 1 argument allowed" we would like to keep it, but have the issue that in several places we use jest-expect-message plugin for an additional message.
Currently we just manually disable the valid-expect rule in those places.

Is ist still planned to add this configurability? Would be awesome :)

**Comment by SimenB** [comment]
A PR would be most welcome 👍
