### ISSUE TITLE
Add rule to require assertion count assertion

### ISSUE THREAD

**Issue by giodamelio** [jest-community/eslint-plugin-jest#40]
I always try to add a [`expect.assertions(<number of assertions>)`](https://facebook.github.io/jest/docs/en/expect.html#expectassertionsnumber) call to the top of every test I write. It helps me keep track of the assertions I am using, and prevents accidental adding and removing of assertions.

I was thinking a rule that requires that assertion for every test would be nice. There is also [`expect.hasAssertions()`](https://facebook.github.io/jest/docs/en/expect.html#expecthasassertions), maybe that should be included in a separate rule? Or maybe not at all, I've never used it because it seems better to specify the count of assertions.

If you guys think this sounds good I would like to give a try at implementing it.

**Comment by SimenB** [comment]
I think that's a great idea!

PR very much welcome 🙂

**Comment by mattphillips** [comment]
Hey @giodamelio if you are using babel with Jest then check out [babel-jest-assertions](https://github.com/mattphillips/babel-jest-assertions) it automates the process of adding `expect.assertions(<number of assertions>)` and `expect.hasAssertions()` to each of your tests.

**Comment by giodamelio** [comment]
That's neat, but it kinda defeats the purpose of why I use them. I want
them as a double check for if I accidentally add or remove asserts.

**Comment by tushardhole** [comment]
@SimenB @giodamelio As this is labeled as `help wanted`. If allowed, I would be happy to work on a PR for this  :smile:

[Here is some](https://github.com/tushardhole/eslint-plugin-jest/commit/b9cd260e483f8d9c343541fea8f3555393afe208) initial work I did.

**Comment by giodamelio** [comment]
Go for it, I was going to take a crack at it but things got busy this
weekend. I'll be looking forward to it.

**Comment by tushardhole** [comment]
Created a PR [here](https://github.com/jest-community/eslint-plugin-jest/pull/43/)
Looking forward for feedback !

**Comment by SimenB** [comment]
Fixed in #43, released in 21.6.0

**Comment by SimenB** [comment]
Docs released in 21.6.1
