### ISSUE TITLE
[new-rule] Enforce top level describe

### ISSUE THREAD

**Issue by bodinsamuel** [jest-community/eslint-plugin-jest#401]
Hello everyone,

Jest, and most testing library, let you write and organise your tests as you want, which is good but it can become a mess with large testing codebase.
(Somewhat similar to #362 and `no-standalone-expect` ) 
It would be super cool to have a rule to enforce a top-level describe and make sure no `test`, `it`, `beforeAll` etc... can live outside this describe.
Maybe it can be something like:
- `require-top-level-describe` 
or 
- merged with `no-standalone-expect` 
   => `no-standalone: ['error', ['test', 'hook', 'expect']]`

What do you think?

**Comment by SimenB** [comment]
Sure, I'm down with that 🙂

**Comment by thomlom** [comment]
Hi! That's something I was looking for as well and I would like to give it a try by opening a PR. Does it work for you? 🙂

**Comment by SimenB** [comment]
Go for it!

**Comment by bodinsamuel** [comment]
That would be awesome @thomlom 🙏

**Comment by bodinsamuel** [comment]
Amazing, this is perfect. A big thanks to both of you 🙏
