### ISSUE TITLE
Lint rule to indicate missing return staement when testing inside promise then or catch block.

### ISSUE THREAD

**Issue by tushardhole** [jest-community/eslint-plugin-jest#41]
**[PORTING THIS ISSUE [FROM](https://github.com/facebook/jest/issues/4843) JEST REPO]**

**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
It is mentioned in the [jest docs](https://facebook.github.io/jest/docs/en/tutorial-async.html) to return a promise when you want to test inside its then or catch block. In case, if a developer misses to add a return statement, then that expectation will not get executed and may result in test which is false positive.

**What is the expected behavior?**
A lint rule

**Please provide your exact Jest configuration and mention your Jest, node, yarn/npm version and operating system.**
jest: 21.2.1
node: 8.0.0
npm: 5.5.1
OS: Sierra (10.12.6)

**Comment by tushardhole** [comment]
ported this [PR](https://github.com/jest-community/eslint-plugin-jest/pull/42) for this issue from jest repo.

**Comment by SimenB** [comment]
Fixed in #42
