### ISSUE TITLE
drop Node.js: 6 support

### ISSUE THREAD

**Issue by FDiskas** [jest-community/eslint-plugin-jest#410]
Remove nodejs v6 from travis and do not support it any more

https://github.com/nodejs/Release#end-of-life-releases

**Comment by SimenB** [comment]
Yeah, we'll do this and some other breaking changes at the same time. Thanks for opening up an issue though, it's good to track this!

**Comment by G-Rath** [comment]
@SimenB is there a rough ETA for when we can do this?

btw I'm happy to handle the general upgrading & updating of everything to new versions once you give the greenlight :)
