### ISSUE TITLE
add support for ESLint v6

### ISSUE THREAD

**Issue by wareczek** [jest-community/eslint-plugin-jest#426]

**Comment by G-Rath** [comment]
I assume this is b/c you get deprecation warnings?

This'll be upgraded as part of #410, as it requires us to drop Node 6 support.

@SimenB is there a rough ETA for that? We're mainly tied to `jest` right?

**Comment by wareczek** [comment]
@G-Rath I mean devDependency support for ^6 there:
https://github.com/jest-community/eslint-plugin-jest/blob/master/package.json#L56

Something like this:
https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb/package.json#L66

**Comment by SimenB** [comment]
`devDependency` doesn't matter for you - it's only local to this repository. The plugin should already support eslint v6 (we use those together at work). it's in our `peerDependency` range already, so there's nothing for us to do here.

https://github.com/jest-community/eslint-plugin-jest/blob/8c850ffaabaf7ead5d96559130f801e6155efdc5/package.json#L25-L27

unless you're getting some kind of warning or error when using this with eslint 6, I'll close this
