### ISSUE TITLE
test.concurrent support

### ISSUE THREAD

**Issue by daniellacosse** [jest-community/eslint-plugin-jest#432]
it appears that the linter ignores `test.concurrent` calls, for example - currently I have the `jest/no-empty-title` rule enabled:

![Screen Shot 2019-10-16 at 16 20 16](https://user-images.githubusercontent.com/3759828/66955798-1cdfbf00-f031-11e9-89b1-ab5ecbdcd681.png)

with just `test`:

![Screen Shot 2019-10-16 at 16 20 28](https://user-images.githubusercontent.com/3759828/66955809-25d09080-f031-11e9-970d-0419466199b4.png)

**Comment by G-Rath** [comment]
Ah yes - I missed that b/c of it's undocumented nature.

From memory it shouldn't be too much trouble to add it, just a matter of finding the time :joy:

**Comment by daniellacosse** [comment]
@G-Rath point me at where i need to do the thing and I'll do the thing

**Comment by G-Rath** [comment]
@daniellacosse from memory, a couple of things need doing:

* `concurrent` needs to be added as a value in the right enu,
* `concurrent` should be checked for what it supports, as while I suspect it is only `test.concurrent`, we need to know if `it.concurrent`, `test.concurrent.only`, `test.concurrent.each`, etc are valid in jest.
* All the rules should be checked, as `jest/no-empty-title` isn't the only one that this affects (or maybe it is - either way, need to check).

**Comment by daniellacosse** [comment]
fyi it's definitely all the rules, i've just included `jest/no-empty-title` as an example.

**Comment by SimenB** [comment]
> but `each` and `concurrent` can't be used together.

that's a bug, mind opening up and issue at facebook/jest?

**Comment by daniellacosse** [comment]
seems there is one - https://github.com/facebook/jest/issues/8985

**Comment by leonardovillela** [comment]
Can i take this issue?

**Comment by SimenB** [comment]
Go for it!

**Comment by G-Rath** [comment]
closed by #498 / #502
