### ISSUE TITLE
Environment key "jest/globals" is unknown

### ISSUE THREAD

**Issue by nickmccurdy** [jest-community/eslint-plugin-jest#44]
I couldn't use `{ "jest/globals": true }` as recommended in the readme, so I'm using the built in Jest env with `{ "jest": true }`.

## Config
```json
{
  "env": { 
    "jest/globals": true
  },
  "extends": [
    "plugin:jest/recommended"
  ]
}
```

## Dependencies
```
purespec@0.0.0 /Users/nick/Repos/purespec
├── eslint@4.14.0
├── eslint-plugin-jest@21.5.0
└── jest@22.0.4
  ```

**Comment by pauloborges** [comment]
I believe ESLint processes the configuration file as it reads it, so try declaring the `env` block after the `extends` block.

**Comment by nickmccurdy** [comment]
I'm still seeing this error after swapping the order.

**Comment by pauloborges** [comment]
I completely misread your code, sorry. If you're extending from the recommended jest plugin (instead of just using the plugin), you shouldn't need to explicitly declare `jest/globals`, since it is already declared by the recommended configuration:

https://github.com/jest-community/eslint-plugin-jest/blob/master/index.js#L21

**Comment by nickmccurdy** [comment]
I didn't notice that, thanks! Removing the Jest env fixed it.

**Comment by yvele** [comment]
Note that I have the same error and I [cannot use the "extends"](https://github.com/eslint/eslint/issues/8813) solution, see https://github.com/jest-community/eslint-plugin-jest/issues/128

**Comment by trusktr** [comment]
> Note that I have the same error and I [cannot use the "extends"](https://github.com/eslint/eslint/issues/8813) solution, see #128

The `extends` in `overrides` is working great lately. F.e., I have the following in my eslintrc just for test files:

```js
  overrides: [
    {
      files: ['**/*.test.js'],
      extends: ['plugin:jest/recommended', 'plugin:jest/style'],
    },
  ],
```

**Comment by yogeshdotnet** [comment]
I have also faced this issue and solved by following steps:

Update Package.json(Remove "react-app/jest" from extends array

"eslintConfig": { "extends": [ "react-app" ] },
Run npm install and check again It works It works fine for me
