### ISSUE TITLE
Enforce it block to begin with lower case test decription

### ISSUE THREAD

**Issue by ismail-syed** [jest-community/eslint-plugin-jest#46]
Some projects prefer that descriptions in `it` blocks beginning with lowercase letters. Is this something that can be enforced as a rule in `eslint-plugin-jest`

eg:

The following patterns are considered warnings: 
```
it('Adds 1 + 2 to equal 3', () => {
  expect(sum(1, 2)).toBe(3);
});
```

These patterns would not be considered warnings:
```
it('adds 1 + 2 to equal 3', () => {
  expect(sum(1, 2)).toBe(3);
});
```

**Comment by SimenB** [comment]
I see no reason not to have a rule for this. @thymikee thoughts?

**Comment by thymikee** [comment]
Makes sense, just don't make it recommended/default 😄
