### ISSUE TITLE
Ability to disable "titleMustBeString" in valid-title rule

### ISSUE THREAD

**Issue by mrtnzlml** [jest-community/eslint-plugin-jest#470]
Hello! :)

We really like [`valid-title` rule](https://github.com/jest-community/eslint-plugin-jest/blob/master/docs/rules/valid-title.md); however, it got too opinionated in latest releases without possibility to configure it (so we had to disable it altogether 😢). More specifically we would need to disable just the `titleMustBeString` part because we sometimes generate the tests dynamically like here: https://github.com/adeira/universe/blob/e6489c667dbed90273d9e7feb3bf494e9fb33241/src/monorepo-scanner/src/scans/WorkspacesDependencies.scan.js#L45

Would you please consider making it configurable? Thank you very much! :)

**Comment by G-Rath** [comment]
@mrtnzlml thanks for raising this issue!

It's actually already possible for `describe` via `ignoreTypeOfDescribeName`.

However, that's about as far as we can go as any further would require us to implement effectively a static analyzer, as we'd have to track variables & identifiers all over the codebase we're linting to determine their type compatibility.

However, you can simply wrap your variable in template strings, like so: `` `${packageJSONLocation}` ``

This is actually a good idea to do anyway, b/c `it` & `test` only support strings - they'll error if you give them anything else, including numbers. So by wrapping in a template literal, you're ensuring `toString` will always be called :)
