### ISSUE TITLE
rename `no-try-expect` to `no-conditional-expect` and add support for `if`

### ISSUE THREAD

**Issue by SimenB** [jest-community/eslint-plugin-jest#482]
Sort of overlaps with `no-if`, but doesn't go as far as banning _all_ conditionals in tests - just assertions in them.

The case we're wanting to guard against with `no-try-expect` is `expect` not being run - I think this is the case for conditionals as well. There are other cases (like iterating through an empty array), but it's probably too hard to properly detect that.

@G-Rath thoughts on this?

**Comment by G-Rath** [comment]
I think that makes sense, and serves as a good general rule for handling conditional expectations (surprise surprise) in whatever form they come in.
