### ISSUE TITLE
[prefer-expect-assertions]: Suggest expect.hasAssertions fix

### ISSUE THREAD

**Issue by G-Rath** [jest-community/eslint-plugin-jest#483]
Requires [suggestion support in typescript-eslint](https://github.com/typescript-eslint/typescript-eslint/pull/1250).

`prefer-expect-assertions` should suggest fixing by adding `expect.hasAssertions`.

We could also do one for `expect.assertions`, but the suggestions api doesn't support any form of user input, and it might upset people having to find out the hard way that `expect.assertions` requires them to actually provide an argument?

@SimenB thoughts?

**Comment by SimenB** [comment]
Agreed - on both points 🙂
