### ISSUE TITLE
[valid-expect]: support specifying custom async matchers

### ISSUE THREAD

**Issue by yatki** [jest-community/eslint-plugin-jest#488]
A bit similar to https://github.com/jest-community/eslint-plugin-jest/issues/54, when we don't await .toReject(), the test returns false positive.

Maybe it's better to have a rule like `await-async-matchers` to cover all this cases.

**Comment by SimenB** [comment]
`toReject` is not part of Jest core, so I don't think built-in support makes sense. We can however maybe take some config either globally er per rule for `asyncMatchers` or some such?

**Comment by yatki** [comment]
Ah yes it was part of the `jest-extended`, wasn't it? Sorry for the issue then.

However, I really liked the idea of accepting a config parameter. What I understood from that is: I can add `.toMyCustomMatcher()` as an async matcher to my .eslintrc config and `valid-expect` rule or a new rule can make sure that those matchers are awaited.

Please let me know if it make sense this way, or did you mean something else? 
🖖

**Comment by G-Rath** [comment]
Have made #1018 implementing this, with the `jest-extended` matchers as the default for the option.
