### ISSUE TITLE
new rule request: valid-each

### ISSUE THREAD

**Issue by benmonro** [jest-community/eslint-plugin-jest#493]
when using a `describe.each` or `test.each` it would be nice to have a rule to ensure that the pretty formatting or `$variable` injection is used to ensure the results are unique.

for example, rule would report on 
`test.each([1,2,3])("Should square the number", () => {...})`
 
but not report on 

`test.each([1,2,3])("Should square %i", () => {...})`

**Comment by G-Rath** [comment]
Closing as a duplicate of #359
