### ISSUE TITLE
add option to not allow .only tests

### ISSUE THREAD

**Issue by asaf-shochet** [jest-community/eslint-plugin-jest#530]
We would like to block the option to run .only tests when building to production.
Is there a way to add this feature?

It's similar to this feature:
https://github.com/jest-community/eslint-plugin-jest/blob/14496756d8e91b6a9642f72a04d87dc0399a8033/docs/rules/no-disabled-tests.md

Thanks!!

**Comment by SimenB** [comment]
That's https://github.com/jest-community/eslint-plugin-jest/blob/master/docs/rules/no-focused-tests.md
