### ISSUE TITLE
Should `fail(e)` be added to global variables that this plugin exports?

### ISSUE THREAD

**Issue by niksajanjic** [jest-community/eslint-plugin-jest#550]
Hi, I have some tests that use `fail(e)` function in async code in case of error. I understand I could just write `done.fail(e)` (which I did) or add `fail` to globals in my eslint configuration, but I was wondering if this should be added to globals by this plugin?

I can see in jest types for the latest version (Jest 25.1) that the type for this global function exists:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/jest/index.d.ts#L1320

Although it is not listed under Jest globals in their API, it is accessible in tests.

**Comment by SimenB** [comment]
No, it's a Jasmine global and not a documented feature in Jest. https://github.com/jest-community/eslint-plugin-jest/blob/master/docs/rules/no-jasmine-globals.md warns against its usage.

DT should probably remove it, or at least deprecate it

**Comment by Doogiemuc** [comment]
In case you stumble upon this because you want to check for an expected throw.   Jest does this differently than jasmine:

The Jasmine way:

    try {
      expectToThrowFunc()
      fail('should have thrown an Error')   // <= Jasmine function fail()
    } catch (error) {
      done("Received expected error")
    }

The Jest way:

    test('throws on octopus', () => {
      expect(() => {
        drinkFlavor('octopus');
      }).toThrow();
    });


https://jestjs.io/docs/en/expect#tothrowerror

**Comment by Doogiemuc** [comment]
Still:  I like the fail() method :-)  It should be included in jest
