### ISSUE TITLE
Bug: jest/no-export triggered on non-test file

### ISSUE THREAD

**Issue by Svish** [jest-community/eslint-plugin-jest#555]
I have the following `jest.json`:

```json
{
  "roots": ["<rootDir>/src"],
  "moduleDirectories": ["node_modules", "src"],
  "testRegex": "^.+\\.spec\\.tsx?$",
  "transform": {
    "^.+\\.(ts|tsx)$": "ts-jest"
  }
}
```

And I have a test helper file `src/util/null/test.ts`:

```ts
type Null = null | undefined;

export default function testNull<R>(fn: (subject: Null) => R, expected: R): void {
  it('should handle `null` as expected', () => {
    expect(fn(null)).toEqual(expected);
  });

  it('should handle `undefined` same as `null`', () => {
    expect(fn(undefined)).toEqual(expected);
  });
}
```

But this helper file triggers the `jest/no-export` rule, even though it's not a test file according to my `testRegex`. 😕

![image](https://user-images.githubusercontent.com/142162/79317000-71db8f80-7f05-11ea-8c85-18ebed81f588.png)

**Comment by G-Rath** [comment]
This is because the rule looks for usage of test suite methods:

> If a file has at least 1 test in it, then this rule will prevent exports.

If you wish to disable the rule in particular files you can place an `/* eslint-disable jest/no-export */` comment at the top of the file, or use [`overrides`](https://eslint.org/docs/user-guide/configuring#disabling-rules-only-for-a-group-of-files).

**Comment by Svish** [comment]
Aah, ok, guess that makes sense. 👍

So that means for shared test utils I will need to disable that rule, no matter what the util file is named.

**Comment by SimenB** [comment]
At some point we might load Jest's config to make these sorts of rules smarter, but at _least_ not until eslint 7 (as it'd have to be async, https://eslint.org/blog/2020/02/whats-coming-in-eslint-7.0.0)

**Comment by G-Rath** [comment]
For anyone coming across this issue in future: please see [this section of the README](https://github.com/jest-community/eslint-plugin-jest#running-rules-only-on-test-related-files) for details on how to configure ESLint to only run our rules on test files..

**Comment by ikonst** [comment]
The motivation of the rule is to prevent inadvertent duplication of tests, which would happen due to the side-effect of importing the module and executing its "top level" code.

If so, can we amend the rule that only describe/it/test statements at module level count for flagging it as a test file?

**Comment by SimenB** [comment]
You should configure the rule to only run on test files. The eslint run will be fater if you do so, im addition to getting rid of this false positive

**Comment by ikonst** [comment]
> You should configure the rule to only run on test files. The eslint run will be fater if you do so, im addition to getting rid of this false positive

Gotcha.

Arguably there's also this gotcha:

- utils.ts
  ```ts
  export const leftPad = ...;
  
  it("does something", () => ...);
  ```

- foo.test.ts
  ```
  import { leftPad } from "utils"; // oops, got more than I bargained for
  ```

but maybe it's more correct to ban top-level `describe` etc. in files not ending in .test?
