### ISSUE TITLE
new rule: require.requireActual -> jest.requireActual

### ISSUE THREAD

**Issue by dylang** [jest-community/eslint-plugin-jest#559]
Jest 26 will no longer support the long deprecated `require.requireActual`, and should transition code to `jest.requireActual` instead.

Same thing with `require.requireMock`.

https://github.com/facebook/jest/commit/d0623eb83b16ef589295d6e759a3519269a80fde

**Comment by SimenB** [comment]
Having a rule for this and autofixing it would be great - we could call it out in the blog post. While it's a simple search and replace, it'd still be nice to do 🙂

**Comment by G-Rath** [comment]
@SimenB any ideas on a good name?

* prefer-jest-require
* no-require-require
* replace-require-require-with-jest-require
* ???

**Comment by SimenB** [comment]
`no-deprecated-functions`? Then we can stick more on it. I wanted to remove a few deprecated functions from the `jest` object as well, but Christoph wanted to wait (aka, FB uses these): https://github.com/facebook/jest/pull/9853

**Comment by SimenB** [comment]
Huge fan of more automation 👍
