### ISSUE TITLE
Support ESLint 7.x

### ISSUE THREAD

**Issue by MichaelDeBoey** [jest-community/eslint-plugin-jest#568]
ESLint v7.0.0 is [released](https://eslint.org/blog/2020/05/eslint-v7.0.0-released) 🎉

It would be awesome to have official ESLint 7 support. 👊
I'm happy to help where I can of course 🙂

**Comment by G-Rath** [comment]
That's perfect timing actually: this will require a new major as it drops support for node 8, which Jest 26 did as well.

@SimenB I've just merged #564 - is there anything else we want before cutting a new major?

**Comment by G-Rath** [comment]
Actually @MichaelDeBoey I just realised we already support eslint@7 since we have a peer dependency on `>= 6` for eslint.

If there's a specific problem you're having let me know, but other I'll close this off since it's already supported :)

**Comment by MichaelDeBoey** [comment]
According to `peerDependencies`, we indeed do, but it's not tested (yet) so not really officially supported

**Comment by G-Rath** [comment]
I've adjusted our test suite to run against eslint 7, so you can consider it officially supported now :)
