### ISSUE TITLE
What should we do in the new major

### ISSUE THREAD

**Issue by G-Rath** [jest-community/eslint-plugin-jest#574]
Just making this meta issue to consolidate what we'd like to land in/around the new major, since we've made some comments in different places:

* Drop Node 8 support (#570)
* Update recommended ruleset (#571)

Depending on time, we could try to do #482.

(I don't think we're in any major rush, since we're not actually blocking anything re jest 26 or eslint 7 - I could be wrong there?)

@SimenB [made some comments too](https://github.com/jest-community/eslint-plugin-jest/pull/572#issuecomment-626128917):

* Dropping eslint 5 support (👍)
* Use the suggestions api for things, such as:
  * `toStrictEqual` - personally I'm happy with that remaining an autofix, because running your tests should tell you if it's actually changed a behaviour (which is also why I wondered if maybe it should be recommended - it strikes me as a bit like `==` vs `===`?)
  * `no-test-callback` should use a suggestion as it's dangerous to autofix
* Renaming `no-test-callback` to `no-done-callback` as it's a more accurate name (👍)

**Comment by SimenB** [comment]
And adding support for hooks (`before{All,Each}`, `after{All,Each}`) for that last one.

Nothing else comes to mind, @thymikee @jeysal ideas?

**Comment by jeysal** [comment]
My only ambition for a major would be the recommended ruleset update :upside_down_face: (but as posted over there in the relevant issue, I'd prefer to add like a billion things to it so.... :sweat_smile: )

**Comment by SimenB** [comment]
https://github.com/jest-community/eslint-plugin-jest/releases/tag/v24.0.0
