### ISSUE TITLE
The utility function "isTestCase" works wrong with some situations.

### ISSUE THREAD

**Issue by 374632897** [jest-community/eslint-plugin-jest#589]
The relative PR is #307 .
See the test case like below(referenced from [no-export.test.ts](https://github.com/jest-community/eslint-plugin-jest/blob/master/src/rules/__tests__/no-export.test.ts#L14)):
```js
{
  valid: [
    'describe("a test", () => { expect(1).toBe(1); })',
    'window.location = "valid"',
    'module.somethingElse = "foo";',
    'export const myThing = "valid"',
    'export default function () {}',
    'module.exports = function(){}',
    'module.exports.myThing = "valid";',
    'export const test = () => true; test("Hello");'
  ],
}
```
The last item of valid array declares a function named "test" and exports it. In this case, the utility function "[isTestCase](https://github.com/jest-community/eslint-plugin-jest/blob/master/src/rules/utils.ts#L649)" makes a wrong check:

```js
export const isTestCase = (
  node: TSESTree.CallExpression,
): node is JestFunctionCallExpression<TestCaseName> =>
  (node.callee.type === AST_NODE_TYPES.Identifier &&
    TestCaseName.hasOwnProperty(node.callee.name)) ||
  (node.callee.type === AST_NODE_TYPES.MemberExpression &&
    node.callee.property.type === AST_NODE_TYPES.Identifier &&
    TestCaseProperty.hasOwnProperty(node.callee.property.name) &&
    ((node.callee.object.type === AST_NODE_TYPES.Identifier &&
      TestCaseName.hasOwnProperty(node.callee.object.name)) ||
      (node.callee.object.type === AST_NODE_TYPES.MemberExpression &&
        node.callee.object.object.type === AST_NODE_TYPES.Identifier &&
        TestCaseName.hasOwnProperty(node.callee.object.object.name))));

```
Once a file has a function named "test" declared and been called in the file, the file will be marked as a test file and this makes it work wrong with the rule "jest/no-export".

![image](https://user-images.githubusercontent.com/15151718/82431994-fbace880-9ac1-11ea-81c4-6aab117b6fe0.png)

**Comment by G-Rath** [comment]
This behaviour is correct: any file that is linted by `eslint-plugin-jest` is assumed to be a test file, as that is the kind of files this plugin is designed to lint.

We do have plans to improve our checking for the jest globals, which would most likely result in this particular case no longer being flagged, but regardless you should use [`overrides`](https://eslint.org/docs/user-guide/configuring#configuration-based-on-glob-patterns) property in your eslint config to apply the rules from this plugin to your test files :)
