### ISSUE TITLE
typescript dependencie is needed

### ISSUE THREAD

**Issue by Sraime** [jest-community/eslint-plugin-jest#601]
When I install the last version of the eslint-plugin-jest, I have this warming :

`npm WARN tsutils@3.17.1 requires a peer of typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta but none is installed. You must install peer dependencies yourself.`

With **npm ls**  I have this error :
`npm ERR! peer dep missing: typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta, required by tsutils@3.17.1 `
and the dependencie : 
```
├─┬ eslint-plugin-jest@23.13.2
│ └─┬ @typescript-eslint/experimental-utils@2.34.0
│   ├── @types/json-schema@7.0.4
│   ├─┬ @typescript-eslint/typescript-estree@2.34.0
│   │ ├─┬ debug@4.1.1
│   │ │ └── ms@2.1.2
│   │ ├── eslint-visitor-keys@1.2.0 deduped
│   │ ├─┬ glob@7.1.6
│   │ │ ├── fs.realpath@1.0.0
│   │ │ ├─┬ inflight@1.0.6
│   │ │ │ ├── once@1.4.0 deduped
│   │ │ │ └── wrappy@1.0.2
│   │ │ ├── inherits@2.0.3 deduped
│   │ │ ├── minimatch@3.0.4 deduped
│   │ │ ├─┬ once@1.4.0
│   │ │ │ └── wrappy@1.0.2 deduped
│   │ │ └── path-is-absolute@1.0.1 deduped
│   │ ├── is-glob@4.0.1 deduped
│   │ ├── lodash@4.17.15 deduped
│   │ ├── semver@7.3.2
│   │ ├─┬ tsutils@3.17.1
│   │ │ └── tslib@1.13.0 deduped
│   │ └── UNMET PEER DEPENDENCY typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta
```

My project do not use typescript at all ... is it required for the plugin ? 

node : v14.4.0
npm : 6.14.5

**Comment by G-Rath** [comment]
TypeScript should not be required for this plugin; that requirement is coming from the latest 2.x version of `@typescript-eslint/typescript-estree`, which is not a package we maintain.

You should open an issue up with them :)

**Comment by codyrobbins** [comment]
Unfortunately they won’t fix it: https://github.com/typescript-eslint/typescript-eslint/issues/1287
