### ISSUE TITLE
Discourage `f` or `x` prefix on specs

### ISSUE THREAD

**Issue by SimenB** [jest-community/eslint-plugin-jest#63]
Instead of doing `fit`, `xit` etc, one should do `it.only` and `it.skip`. Same for `describe`.

Should also be fixable

**Comment by ranyitz** [comment]
I can also take this issue as it closely related to #12

### name suggestions:
1. `prefer-only-skip`
2. `no-fx-prefix`

**Comment by SimenB** [comment]
I like the first one :) @thymikee?

**Comment by thymikee** [comment]
@SimenB yup, I'm on your side on this :)
