### ISSUE TITLE
feature request: disallow it.only

### ISSUE THREAD

**Issue by bradvogel** [jest-community/eslint-plugin-jest#640]
I'm sure this has been requested...

Is there an eslint rule to disallow `it.only`. It's common for developers to check that in accidentally.

**Comment by G-Rath** [comment]
Yup, there is - it's called [`no-focused-tests`](https://github.com/jest-community/eslint-plugin-jest/blob/master/docs/rules/no-focused-tests.md) :)

**Comment by bradvogel** [comment]
thanks!
