### ISSUE TITLE
How should I fail in an async test

### ISSUE THREAD

**Issue by dpinol** [jest-community/eslint-plugin-jest#657]
Imagine that I need an assert so that I never reach somewhere (eg. a callback function is never called)

If I use fail(), I get
`Illegal usage of `fail`, prefer throwing an error, or the `done.fail` callback  jest/no-jasmine-globals`
If I use done.fail, I get
`Use await instead of callback in async functions  jest/no-done-callback`

what do you recommend?

thanks

**Comment by SimenB** [comment]
`throw new Error('Unreachable')`
