### ISSUE TITLE
"all" config includes deprecated rules

### ISSUE THREAD

**Issue by jdanil** [jest-community/eslint-plugin-jest#663]
I think I just missed the boat for a major release, but I just wanted to clarify how deprecated rules are handled in this plugin.

Currently the "all" config includes all rules in the `rules` directory, including deprecated rules that still exist in the source code.

```typescript
const rulesDir = join(__dirname, 'rules');
const excludedFiles = ['__tests__', 'utils'];

const rules = readdirSync(rulesDir)
  .map(rule => parse(rule).name)
  .filter(rule => !excludedFiles.includes(rule))
  .reduce<Record<string, RuleModule>>(
    (acc, curr) => ({
      ...acc,
      [curr]: importDefault(join(rulesDir, curr)) as RuleModule,
    }),
    {},
  );

const allRules = Object.keys(rules).reduce<
  Record<string, TSESLint.Linter.RuleLevel>
>((rules, key) => ({ ...rules, [`jest/${key}`]: 'error' }), {});
```

I thought that those deprecated rules might get removed in the next major release. Is that generally the case, or are they expected to remain indefinitely?

Would it make sense for `allRules` to filter on `rule.meta.deprecated`?

**Comment by SimenB** [comment]
> I thought that those deprecated rules might get removed in the next major release. Is that generally the case, or are they expected to remain indefinitely?

Yeah, they were supposed to go away, we just forgot 😅 

https://github.com/jest-community/eslint-plugin-jest/pull/579#issuecomment-687494570
#661

> Would it make sense for `allRules` to filter on `rule.meta.deprecated`?

That might make sense regardless of them being removed in the next major or not. @G-Rath thoughts?

**Comment by G-Rath** [comment]
> thoughts

Let's not forget to remove deprecated rules in future majors 😅

Also, I think this sets a predicents we should be careful of, as it's arguably breaking a similar but more subtle way to us removing the deprecated rules in a minor.

I've made a PR for this :)

**Comment by SimenB** [comment]
We explicitly say `all` is not covered by semver in the readme: https://github.com/jest-community/eslint-plugin-jest/blob/master/README.md#all

**Comment by jdanil** [comment]
Cheers fellas!
