### ISSUE TITLE
[valid-title] Feature: User-specified error message for jest/valid-title::mustMatch

### ISSUE THREAD

**Issue by eli88fine** [jest-community/eslint-plugin-jest#688]
The error message for `jest/valid-title` using `mustMatch` is not especially helpful to new users to a codebase that has that rule implemented. It just displays the regular expression.

Would you be open to a Pull Request to allow the eslint config for the rule to accept an [optional] plain text description that would be included in the error message to help make it clearer to people seeing the ESLint error what they did wrong and how to fix it?

**Comment by G-Rath** [comment]
I'm not against this - it would increase the complexity a bit, but no immediate blockers spring to mind so happy to explore this.
