### ISSUE TITLE
Considering adding codecov integration

### ISSUE THREAD

**Issue by ranyitz** [jest-community/eslint-plugin-jest#69]
What do you say about adding [codecov](https://codecov.io/) integration?
It would be nice to know the coverage changes for each PR.

**Comment by SimenB** [comment]
Yeah, we should set this up. @thymikee preferences on service?

Also see #67

**Comment by thymikee** [comment]
Maybe we could use Danger to read the coverage saved as artifact? Some reference (but without Danger): https://github.com/callstack/linaria/pull/200
Anyway I'm good with reporting coverage in PRs.

**Comment by SimenB** [comment]
Yeah, that'd be cool!

@orta is there a danger plugin for code coverage? 😀

**Comment by macklinu** [comment]
I don't believe there is a code coverage Danger plugin, but there is an open issue for danger-plugin-jest to support posting code coverage (https://github.com/macklinu/danger-plugin-jest/issues/26).

If this is something that can be added to this repo's dangerfile and transferred over to danger-plugin-jest, or if anyone is interested in contributing a PR to danger-plugin-jest to resolve this, that'd be awesome. 😄

**Comment by SimenB** [comment]
As we now have 100% coverage, CI will fail if it dips. Could still be nice with an integration, though

**Comment by G-Rath** [comment]
@SimenB is there anything left to be done on this ticket? I'm happy with the CIs we've got in place (I think codecov is ok, but a bit spammy of the inbox - would be cool if GHA had supported annotating coverage)

**Comment by SimenB** [comment]
I'm down with adding https://github.com/codecov/codecov-action or something. It's nice to be able to browse the coverage report. Not sure if it accepts an option to not post a comment on the PR? GitHub checks is enough for me
