### ISSUE TITLE
jest/expect-expect more flexible wildcard syntax

### ISSUE THREAD

**Issue by osdiab** [jest-community/eslint-plugin-jest#702]
I just updated `eslint-plugin-jest` and am getting a lot of errors from this. My team often creates test-wide custom helper expect functions like `expectOneMatchingAttribute()` or `expectSatisfiesSomethingComplicated()` that do a number of checks at once, but basically serve as an expectation - i'd love to be able to blanket consider any function that starts with `expect` as an expectation. The way the wildcard support works for the `assertFunctionNames` parameter of the `jest/expect-expect` doesn't seem to have a way to do this, so i'd have to add different config for every test file that does this, which is a pain. I personally thought that the pattern `expect*` should have been able to match it, but that doesn't work. Open to PRs to allow it to do that?

**Comment by SimenB** [comment]
Definitely open for PRs allowing a pattern 👍 I don't think `expect*` should be enabled out of the box, but an option allowing you to configure that sounds like a good idea

**Comment by G-Rath** [comment]
[This is already supported](https://github.com/jest-community/eslint-plugin-jest/blob/master/src/rules/__tests__/expect-expect.test.ts#L173) :)

I'm going to close this issue, but happy to re-open if you're having trouble with a particular pattern - I ran the tests with `expect*` to confirm that should allow `expectOneMatchingAttribute` & `expectSatisfiesSomethingComplicated`.
