### ISSUE TITLE
24.1.2 - breaking change? Prefer using 'test' instead of 'it' within describe (jest/consistent-test-it)

### ISSUE THREAD

**Issue by genrym** [jest-community/eslint-plugin-jest#711]
Hi. 
After upgrading to version `24.1.2` - we started to get the following:

`Prefer using 'test' instead of 'it' within describe (jest/consistent-test-it)`

Was it an expected change in this version?

**Comment by SimenB** [comment]
@genrym could you share a code snippet that doesn't fail on 24.1.0 but fails with 24.1.1 and 24.1.2? Would like to add a regression test if it's misbehaving
