### ISSUE TITLE
How to test click events with  prefer-called-with

### ISSUE THREAD

**Issue by tiagoporto** [jest-community/eslint-plugin-jest#724]
I would like to check if the `onClick` function is called. 

```jsx
const onClickMock = jest.fn()
const { getByTestId } = render(<button onClick={onClickMock} data-testid="close-menu-button">Test</button>)
const closeButton = getByTestId('close-menu-button')

fireEvent.click(closeButton)
expect(onClickMock).toHaveBeenCalledWith()
```

When I use `toHaveBeenCalledWith`, I get the following error.

<img width="850" alt="Screen Shot 2020-12-05 at 11 52 00 AM" src="https://user-images.githubusercontent.com/3688905/101246171-55889f00-36f0-11eb-811a-c332ede29d38.png">

Is there a good practice to handle this cases?
I'm using jest with Testing library

Thanks

**Comment by G-Rath** [comment]
I think this is a question better asked over at [`react-testing-library`](https://github.com/testing-library/react-testing-library#-questions), on either stackoverflow or on their Discord :)
