### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received an instance of Array

### ISSUE THREAD

**Issue by Doogiemuc** [jest-community/eslint-plugin-jest#736]
When I include eslint-plugin-jest in my project, I get this error:

```
>npm run lint

> populating-cache@3.1.0 lint D:\Coding\git-repos\populating-cache
> eslint .


Oops! Something went wrong! :(

ESLint: 7.16.0

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received an instance of Array
    at validateString (internal/validators.js:124:11)
    at Object.isAbsolute (path.js:353:5)
    at isFilePath (D:\Coding\git-repos\populating-cache\node_modules\@eslint\eslintrc\lib\config-array-factory.js:131:14)
    at D:\Coding\git-repos\populating-cache\node_modules\@eslint\eslintrc\lib\config-array-factory.js:899:17
```

**package.json:**
    "eslint": "7.16.0",

Is this a version/dependency mismatch?

**Comment by G-Rath** [comment]
Could you please provide more information - specifically, what version of `eslint-plugin-jest` you've got installed and your eslint config?

could you also ensure you've got a fresh node_modules with `npm ci`?

**Comment by maksimhodasevich** [comment]
have the same issue..created file with `npx eslint --init` 
"eslint-plugin-jest": "^24.1.3"
"eslint": "^7.19.0",
all node_modules are fresh

**Comment by maksimhodasevich** [comment]
you can try to upgrade your node version..helps me

**Comment by SimenB** [comment]
No response, so closing this. Feel free to open up a new issue if you're still seeing this issue (please include a reproduction if you do so 👍)
