### ISSUE TITLE
Autofix for xdescribe.each is wrong

### ISSUE THREAD

**Issue by fabb** [jest-community/eslint-plugin-jest#776]
Autofix for `xdescribe.each` replaces by `describe.each.skip` which does not exist. It should be `describe.skip.each`.

https://jestjs.io/docs/uk/api#describeskipeachtablename-fn

**Comment by fabb** [comment]
And `describe.skip.each` does not trigger the rule `jest/no-disabled-tests`.

**Comment by G-Rath** [comment]
The issue with `no-test-prefixes` has been fixed by #722
