### ISSUE TITLE
New rule: no-async-without-await

### ISSUE THREAD

**Issue by macklinu** [jest-community/eslint-plugin-jest#81]
A follow up to the discussion in https://github.com/jest-community/eslint-plugin-jest/pull/78#discussion_r167959193, it could be nice to have a rule like Ava's [`no-async-fn-without-await`](https://github.com/avajs/eslint-plugin-ava/blob/master/docs/rules/no-async-fn-without-await.md).

**Comment by alexilyaev** [comment]
Is this what you mean?  
https://eslint.org/docs/rules/require-await

**Comment by SimenB** [comment]
People can use `overrides` to enable/disable the core rule for any files they want
