### ISSUE TITLE
Get to 100% test coverage

### ISSUE THREAD

**Issue by SimenB** [jest-community/eslint-plugin-jest#86]
In #67 thresholds were added, but I was unable to set them at 100 as we don't have coverage. Help reaching it would be greatly appreciated!

**Comment by SimenB** [comment]
With #88 we're getting really close! Only a couple of branches left

**Comment by tushardhole** [comment]
@SimenB I will look into missing branch coverage for valid-expect-in-promise.js

**Comment by tushardhole** [comment]
@SimenB I will also check remaining files for 100% coverage.

**Comment by tushardhole** [comment]
Created PR [here](https://github.com/jest-community/eslint-plugin-jest/pull/89)

**Comment by SimenB** [comment]
Woo! ❤️
