### ISSUE TITLE
no-deprecated-functions rule probably should try to find jest from its own directory upwards, not from cwd

### ISSUE THREAD

**Issue by billbalm** [jest-community/eslint-plugin-jest#886]
If we have multiple projects in a parent directory like this:

```
workspace/
├── project1/
│   └── node_modules/
│       ├── eslint/
│       ├── eslint-plugin-jest/
│       └── jest/
└── project2/
    └── node_modules/
        ├── eslint/
        ├── eslint-plugin-jest/
        └── jest/
```

Then if we run eslint in `project1` from `workspace` folder, `require.resolve` throws
because from working directory it can't resolve `jest/package.json`. Now if we remove this line it
works obviously: https://github.com/jest-community/eslint-plugin-jest/blob/main/src/rules/no-deprecated-functions.ts#L45

Easy to reproduce with @dbaeumer's plugin for VSCode.
If we open `workspace` folder above in VSCode, no-deprecated-functions rule throws.

Not sure if there's a strong reason to resolve jest from `process.cwd()`. If not, can we remove that line?

**Comment by G-Rath** [comment]
It's because I was silly 😅 I can't remember why I actually included it, but I've tried it locally without and nothing seems to have broken so far.

I'm going to make a draft PR removing it - would you mind applying it to a few projects (ideally both monorepo and not) and seeing if it all still works? (both in any editor tools you use and from thecommand linee)

**Comment by billbalm** [comment]
Awesome @G-Rath 

I tested it a bit on my end as well and it behaves okay.

Simply `const jestPath = require.resolve('jest/package.json')` resolves it to the nearest `node_modules/jest` folder by default and respects `module.paths`.

With `NODE_PATH` set, e.g.  `export NODE_PATH=$(node root -g)`, it even finds global jest if not locally installed.

Thanks
