### ISSUE TITLE
Add rule disallowing importing `jest`

### ISSUE THREAD

**Issue by SimenB** [jest-community/eslint-plugin-jest#90]
See https://github.com/facebook/jest/issues/4613, this is apparently a footgun.

We might take it one step further an yell at all assignments to a `jest` object as it might mess up static analysis, thus negating hoisting of `jest.mock`?

But at least a rule for not importing `jest` (as it doesn't export anything) makes sense.

**Comment by brianlmacdonald** [comment]
@SimenB can I take this one?

**Comment by SimenB** [comment]
Go for it! 🙂
