### ISSUE TITLE
Check for `jest-cli` instead of `jest` to get version

### ISSUE THREAD

**Issue by piranna** [jest-community/eslint-plugin-jest#924]
To check for `jest` version, it's being done a `require.resolve()` to the `jest` package, but this was long deprecated in benefict of `jest-cli`, and now it only calls it. Check should be changed to the new package, instead of requiring to import and almost empty package that does nothing.

**Comment by G-Rath** [comment]
I'm going to close this as I think we confirmed that `jest` is the right package to be checking.
