### ISSUE TITLE
Jest plugin not recognized in .eslintrc.js

### ISSUE THREAD

**Issue by yyaddaden** [jest-community/eslint-plugin-jest#982]
Hi, 

Based on the documentation, I installed `eslint-plugin-jest` and I added the configuration on `.eslintrc.js` : 

module.exports = {
    "env": {
        "browser": true,
        "es2021": true,
        "jest/globals": true
    },
    "extends": [
        "eslint:recommended",
        "plugin:react/recommended",
        "plugin:react-redux/recommended",
        "plugin:flowtype/recommended",
        'plugin:jest/recommended'
    ],
    "parserOptions": {
        "ecmaFeatures": {
            "jsx": true
        },
        "ecmaVersion": 13,
        "sourceType": "module"
    },
    "plugins": [
        "react",
        "react-redux",
        "flowtype",
        "jest"
    ],
    "rules": {
        "react-redux/prefer-separate-component-file": 0
    }
};

But I got this error when launching `npx eslint src/**` : 

Oops! Something went wrong! :( 

ESLint: 8.2.0

TypeError: Failed to load plugin 'jest' declared in '.eslintrc.js': Class extends value undefined is not a constructor or null
Referenced from: C:\Users\yaddya01\Desktop\basic-to-do-list-redux-jest-app\.eslintrc.js
    at Object.<anonymous> (C:\Users\yaddya01\Desktop\basic-to-do-list-redux-jest-app\node_modules\@typescript-eslint\experimental-utils\dist\ts-eslint\CLIEngine.js:12:34)
    at Module._compile (C:\Users\yaddya01\Desktop\basic-to-do-list-redux-jest-app\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (C:\Users\yaddya01\Desktop\basic-to-do-list-redux-jest-app\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.<anonymous> (C:\Users\yaddya01\Desktop\basic-to-do-list-redux-jest-app\node_modules\@typescript-eslint\experimental-utils\dist\ts-eslint\index.js:14:14)
    at Module._compile (C:\Users\yaddya01\Desktop\basic-to-do-list-redux-jest-app\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)

**Comment by G-Rath** [comment]
You need to update `@typescript-eslint` (if that doesn't work, please open a new issue with a proper reproduction e.g. include your `package.json`)

**Comment by CorinneKelly** [comment]
(Posting to help those coming here looking for answers) What worked for me was updating `eslint-plugin-jest` library

**Comment by JESii** [comment]
(Also, I had to upgrade `eslint-plugin-import` to V2.26.0 -- V2.22.2 didn't work for me)

**Comment by fernandocanizo** [comment]
Stomped into this same error message:
```
Failed to load plugin 'jest' declared in '../.eslintrc.js': Class extends value undefined is not a constructor or null
Referenced from: /some/path/to/my/project/.eslintrc.js
```
Several searches and StackOverflow answers directed me to update all my devDependencies since, like this issue, people tell different updates worked for them. So I started upgrading dependency by dependency and checking if it was solved after each upgrade, but the problem didn't disappeared.

My upgrades diff:
```
$ git diff package.json
package.json --- JSON
29     "morgan": "^1.8.1"                                                 29     "morgan": "^1.8.1"
30   },                                                                   30   },
31   "devDependencies": {                                                 31   "devDependencies": {
32     "babel-jest": "26.6.0",                                            32     "babel-jest": "^29.5.0",
33     "eslint": "^7.32.0",                                               33     "eslint": "^8.37.0",
34     "eslint-config-standard": "^16.0.3",                               34     "eslint-config-standard": "^17.0.0",
35     "eslint-plugin-import": "^2.24.2",                                 35     "eslint-plugin-import": "^2.27.5",
36     "eslint-plugin-jest": "^24.4.2",                                   36     "eslint-plugin-jest": "^27.2.1",
37     "eslint-plugin-node": "^11.1.0",                                   37     "eslint-plugin-node": "^11.1.0",
38     "eslint-plugin-promise": "^5.1.0",                                 38     "eslint-plugin-promise": "^6.1.1",
39     "eslint-plugin-react": "^7.26.0",                                  39     "eslint-plugin-react": "^7.32.2",
40     "eslint-plugin-react-hooks": "^4.2.0",                             40     "eslint-plugin-react-hooks": "^4.6.0",
41     "faker": "^3.1.0",                                                 41     "faker": "^3.1.0",
42     "jest": "26.6.0",                                                  42     "jest": "^29.5.0",
43     "nodemon": "^1.11.0",                                              43     "nodemon": "^1.11.0",
44     "pre-commit": "^1.2.2"                                             44     "pre-commit": "^1.2.2"
45   }                                                                    45   }
```
Basically I updated everything jest/eslint related (eslint-plugin-node stayed the same because it was already at its most updated version)

My `.eslintrc.js` is:
```javascript
module.exports = {
  env: {
    browser: true,
    commonjs: true,
    es2021: true,
    node: true
  },
  extends: [
    'plugin:react/recommended',
    'plugin:jest/recommended',
    'standard'
  ],
  parserOptions: {
    ecmaFeatures: {
      jsx: true
    },
    ecmaVersion: 12
  },
  plugins: [
    'react', 'react-hooks', 'jest'
  ],
  rules: {
  }
}
```
**Conclusion:** just upgrading didn't work for me.

Any ideas?

**Comment by fernandocanizo** [comment]
Oh well, I missed another step: removed `node_modules` and reinstalled and error disappeared. It seems there was some weird link (I'm using `pnpm`) that was causing the problem. I hope this helps the next one.

**Comment by aimalamiri** [comment]
`npm update --force` worked for me.
