### ISSUE TITLE
[new rule] `prefer-to-comparison`

### ISSUE THREAD

**Issue by sapphi-red** [jest-community/eslint-plugin-jest#989]
Prefer `expect(a).toBeGreaterThan(b)` rather than `expect(a > b).toBe(true)`, which has a better error message.

Also the same with:

- `expect(a).toBeGreaterThanOrEqual(b)`
- `expect(a).toBeLessThan(b)`
- `expect(a).toBeLessThanOrEqual(b)`

**Comment by G-Rath** [comment]
Should this be a new rule, or part of [`prefer-to-be`](https://github.com/jest-community/eslint-plugin-jest/blob/main/docs/rules/prefer-to-be.md) 🤔

**Comment by sapphi-red** [comment]
I feel this is simillar to [`prefer-to-contain`](https://github.com/jest-community/eslint-plugin-jest/blob/main/docs/rules/prefer-to-contain.md), so I thought this should be a new rule.
