### ISSUE TITLE
[prefer-hooks-on-top]: allow enforcing order of hooks

### ISSUE THREAD

**Issue by dkMorlok** [jest-community/eslint-plugin-jest#992]
I using this rule https://github.com/jest-community/eslint-plugin-jest/blob/main/docs/rules/prefer-hooks-on-top.md 

Would be nice have possibility to specify exact order for hooks, for example:
`order: ['beforeAll', 'beforeEach', 'afterEach', 'afterAll']`

**Comment by G-Rath** [comment]
I'm thinking this _might_ be better as it's own rule... 🤔

**Comment by aaron012** [comment]
Hi @G-Rath, I am interested in having this as a separate rule as well. Would you accept a pull request to add this? I have made a basic version locally and I can continue my work on it to create a pull request.

**Comment by G-Rath** [comment]
@aaron012 go for it! I made a start implementing this as `prefer-hooks-in-order` but didn't get around to finishing it - the branch is [here](https://github.com/jest-community/eslint-plugin-jest/tree/prefer-hooks-in-order) if you want to use it (it's already got the documentation written, and the tests could be useful)
